-- Soldiers Training — pending remote deploy (fases 1–8 intelligence / catalog / media / athlete network)
-- Project: zphtvrsxlhfgltwgbreu
-- Paste into Supabase SQL Editor → Run
-- Generated: 2026-09-21T12:00:05.3787251-03:00


-- ========== 20261008120000_fase1_intelligence_convergence.sql ==========
-- FASE 1 Intelligence Convergence: day's assembled DecisionContextSnapshot
-- Envelope for UI/Coach hydration. recommendation_decisions remains the learning ledger.

CREATE TABLE IF NOT EXISTS public.decision_context_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
  engine TEXT NOT NULL DEFAULT 'decision_v1',
  snapshot_version INTEGER NOT NULL DEFAULT 1,
  customer360_version BIGINT,
  stale360 BOOLEAN NOT NULL DEFAULT false,
  input_fingerprint TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT decision_context_snapshots_user_date_uidx UNIQUE (user_id, date)
);

CREATE INDEX IF NOT EXISTS decision_context_snapshots_user_date_idx
  ON public.decision_context_snapshots (user_id, date DESC);

CREATE INDEX IF NOT EXISTS decision_context_snapshots_user_updated_idx
  ON public.decision_context_snapshots (user_id, updated_at DESC);

ALTER TABLE public.decision_context_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.decision_context_snapshots FROM anon, authenticated;
GRANT ALL ON TABLE public.decision_context_snapshots TO service_role;


INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20261008120000', '20261008120000_fase1_intelligence_convergence')
ON CONFLICT (version) DO NOTHING;


-- ========== 20261009120000_fase2_decision_attribution.sql ==========
-- FASE 2 Decision Outcome Attribution
-- decision_actions = expected vs actual execution (UNIQUE decision_id)
-- decision_outcomes += window / attribution / learning_signal
-- Historical fan-out rows stay attribution_type=unknown and are deduped before UNIQUE.

CREATE TABLE IF NOT EXISTS public.decision_actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  decision_id UUID NOT NULL REFERENCES public.recommendation_decisions(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  expected_action TEXT NOT NULL,
  actual_action TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  entity_type TEXT,
  entity_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT decision_actions_decision_uidx UNIQUE (decision_id),
  CONSTRAINT decision_actions_status_chk CHECK (
    status IN ('pending', 'started', 'completed', 'skipped', 'rejected', 'modified')
  )
);

CREATE INDEX IF NOT EXISTS decision_actions_user_date_idx
  ON public.decision_actions (user_id, date DESC);

CREATE INDEX IF NOT EXISTS decision_actions_user_status_idx
  ON public.decision_actions (user_id, status);

ALTER TABLE public.decision_actions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.decision_actions FROM anon, authenticated;
GRANT ALL ON TABLE public.decision_actions TO service_role;

ALTER TABLE public.decision_outcomes
  ADD COLUMN IF NOT EXISTS action_id UUID REFERENCES public.decision_actions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS outcome_window TEXT NOT NULL DEFAULT 'd0',
  ADD COLUMN IF NOT EXISTS attribution_type TEXT NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS attribution_confidence NUMERIC(4, 3),
  ADD COLUMN IF NOT EXISTS outcome_quality TEXT NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS learning_signal TEXT;

UPDATE public.decision_outcomes
SET
  outcome_window = COALESCE(NULLIF(outcome_window, ''), 'd0'),
  attribution_type = COALESCE(NULLIF(attribution_type, ''), 'unknown'),
  outcome_quality = COALESCE(NULLIF(outcome_quality, ''), 'unknown')
WHERE TRUE;

-- Keep oldest row per (decision_id, outcome_type, outcome_window) before UNIQUE.
DELETE FROM public.decision_outcomes
WHERE id IN (
  SELECT id FROM (
    SELECT id,
      ROW_NUMBER() OVER (
        PARTITION BY decision_id, outcome_type, outcome_window
        ORDER BY created_at ASC, id ASC
      ) AS rn
    FROM public.decision_outcomes
  ) ranked
  WHERE ranked.rn > 1
);

CREATE UNIQUE INDEX IF NOT EXISTS decision_outcomes_decision_type_window_uidx
  ON public.decision_outcomes (decision_id, outcome_type, outcome_window);

CREATE INDEX IF NOT EXISTS decision_outcomes_action_id_idx
  ON public.decision_outcomes (action_id)
  WHERE action_id IS NOT NULL;

COMMENT ON TABLE public.decision_actions IS
  'Expected vs actual action for one recommendation_decisions row. UNIQUE(decision_id).';

COMMENT ON COLUMN public.decision_outcomes.attribution_type IS
  'direct | indirect | weak | unknown. Legacy fan-out rows are unknown and must not train.';

COMMENT ON COLUMN public.decision_outcomes.outcome_window IS
  'd0 | d1 | d3 | d7 relative to the decision date (user timezone key).';


INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20261009120000', '20261009120000_fase2_decision_attribution')
ON CONFLICT (version) DO NOTHING;


-- ========== 20261010120000_fase3_unified_exercise_catalog.sql ==========
-- Fase 3 â€” Unified Exercise Catalog
-- Overlay columns + Soldiers lote 1 seed. ON CONFLICT DO NOTHING preserves existing CMS rows.
-- Do not import third-party catalogs.

ALTER TABLE public.catalog_exercises
  ADD COLUMN IF NOT EXISTS canonical_name text,
  ADD COLUMN IF NOT EXISTS display_name_en text,
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS aliases text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS search_terms text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS equipment_inventory text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS exercise_family text,
  ADD COLUMN IF NOT EXISTS movement_family text,
  ADD COLUMN IF NOT EXISTS progression_family text,
  ADD COLUMN IF NOT EXISTS regression_family text,
  ADD COLUMN IF NOT EXISTS contraindication_tags text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS media_id text,
  ADD COLUMN IF NOT EXISTS media_status text,
  ADD COLUMN IF NOT EXISTS animation_spec jsonb;

UPDATE public.catalog_exercises
SET canonical_name = id
WHERE canonical_name IS NULL OR btrim(canonical_name) = '';

UPDATE public.catalog_exercises
SET media_id = id
WHERE media_id IS NULL OR btrim(media_id) = '';

UPDATE public.catalog_exercises
SET media_status = 'missing'
WHERE media_status IS NULL OR btrim(media_status) = '';

CREATE INDEX IF NOT EXISTS catalog_exercises_aliases_gin
  ON public.catalog_exercises USING gin (aliases);

CREATE INDEX IF NOT EXISTS catalog_exercises_search_terms_gin
  ON public.catalog_exercises USING gin (search_terms);

INSERT INTO public.catalog_exercises (
  id,
  name,
  muscle_group,
  equipment,
  swap_group,
  joints,
  unit,
  base_load,
  priority,
  primary_muscles,
  secondary_muscles,
  movement_pattern,
  difficulty,
  planner_eligible,
  active,
  instructions,
  alternative_ids,
  canonical_name,
  version,
  media_id,
  media_status
) VALUES
(
    'supino-reto',
    'Supino reto',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    50,
    1,
    ARRAY['peito']::text[],
    ARRAY['triceps', 'ombros']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Deite no banco com os pÃ©s no chÃ£o e as escÃ¡pulas estÃ¡veis.', 'Segure a barra um pouco alÃ©m da largura dos ombros.', 'DesÃ§a a barra de forma controlada atÃ© prÃ³ximo do peito.', 'Empurre atÃ© a extensÃ£o dos braÃ§os sem perder o contato das costas no banco.']::text[],
    '{}'::text[],
    'supino-reto',
    1,
    'supino-reto',
    'missing'
  ),
(
    'supino-inclinado-halter',
    'Supino inclinado com halteres',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    20,
    2,
    ARRAY['peito']::text[],
    ARRAY['triceps', 'ombros']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Ajuste o banco entre 30 e 45 graus.', 'Halteres na linha do peito, palmas Ã  frente.', 'Empurre para cima convergindo levemente no topo.', 'DesÃ§a atÃ© o peito alongar sem perder estabilidade do ombro.']::text[],
    '{}'::text[],
    'supino-inclinado-halter',
    1,
    'supino-inclinado-halter',
    'missing'
  ),
(
    'flexao',
    'FlexÃ£o de braÃ§o',
    'peito',
    'ambos',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps', 'core']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['MÃ£os na largura dos ombros, corpo em linha reta.', 'DesÃ§a o peito em direÃ§Ã£o ao chÃ£o.', 'Empurre atÃ© os braÃ§os estenderem.', 'Mantenha o core firme o tempo todo.']::text[],
    '{}'::text[],
    'flexao',
    1,
    'flexao',
    'missing'
  ),
(
    'crucifixo',
    'Crucifixo',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    14,
    1,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Deite no banco com halteres acima do peito, cotovelos levemente flexionados.', 'Abra os braÃ§os em arco atÃ© sentir o peito alongar.', 'Feche o arco atÃ© os halteres se aproximarem no topo.', 'NÃ£o deixe os cotovelos travarem.']::text[],
    '{}'::text[],
    'crucifixo',
    1,
    'crucifixo',
    'missing'
  ),
(
    'supino-declinado',
    'Supino declinado',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    45,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Trave os pÃ©s no banco declinado.', 'DesÃ§a a barra Ã  parte baixa do peito.', 'Empurre em linha controlada.', 'NÃ£o deixe os ombros subirem.']::text[],
    '{}'::text[],
    'supino-declinado',
    1,
    'supino-declinado',
    'missing'
  ),
(
    'flexao-diamante',
    'FlexÃ£o diamante',
    'peito',
    'casa',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'advanced',
    true,
    true,
    ARRAY['Junte os indicadores e polegares em losango sob o peito.', 'DesÃ§a com cotovelos junto ao tronco.', 'Empurre sem abrir o losango.', 'Mantenha o quadril alinhado.']::text[],
    '{}'::text[],
    'flexao-diamante',
    1,
    'flexao-diamante',
    'missing'
  ),
(
    'crossover-polia',
    'Crossover na polia',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    12,
    2,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Passo Ã  frente, tronco estÃ¡vel.', 'Traga as polias em arco atÃ© a frente do peito.', 'Controle a volta.', 'Cotovelos levemente flexionados.']::text[],
    '{}'::text[],
    'crossover-polia',
    1,
    'crossover-polia',
    'missing'
  ),
(
    'peck-deck',
    'Peck deck',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    30,
    2,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Encoste as escÃ¡pulas no encosto.', 'Feche os braÃ§os atÃ© as almofadas se tocarem.', 'Abra com controle.', 'NÃ£o encoste os cotovelos atrÃ¡s da linha do tronco.']::text[],
    '{}'::text[],
    'peck-deck',
    1,
    'peck-deck',
    'missing'
  ),
(
    'supino-maquina',
    'Supino na mÃ¡quina',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    40,
    2,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Ajuste o assento para as pegadas na linha do peito.', 'Empurre atÃ© a extensÃ£o controlada.', 'Volte sem perder o contato das costas.', 'Expire na subida.']::text[],
    '{}'::text[],
    'supino-maquina',
    1,
    'supino-maquina',
    'missing'
  ),
(
    'flexao-inclinada',
    'FlexÃ£o inclinada',
    'peito',
    'casa',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['MÃ£os em um banco ou parede, corpo alinhado.', 'DesÃ§a o peito em direÃ§Ã£o ao apoio.', 'Empurre atÃ© estender.', 'Ãštil para quem estÃ¡ comeÃ§ando.']::text[],
    '{}'::text[],
    'flexao-inclinada',
    1,
    'flexao-inclinada',
    'missing'
  ),
(
    'crucifixo-inclinado',
    'Crucifixo inclinado',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    10,
    2,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Banco 30 graus, arco amplo com cotovelos moles.', 'Abra atÃ© o peito alongar.', 'Feche sem bater os halteres.', 'Evite hiperextensÃ£o do ombro.']::text[],
    '{}'::text[],
    'crucifixo-inclinado',
    1,
    'crucifixo-inclinado',
    'missing'
  ),
(
    'flexao-declinada',
    'FlexÃ£o declinada',
    'peito',
    'casa',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['ombros', 'triceps']::text[],
    'press',
    'advanced',
    true,
    true,
    ARRAY['PÃ©s elevados em um banco.', 'DesÃ§a o peito ao chÃ£o.', 'Empurre mantendo o core.', 'NÃ£o deixe o quadril cair.']::text[],
    '{}'::text[],
    'flexao-declinada',
    1,
    'flexao-declinada',
    'missing'
  ),
(
    'barra-fixa',
    'Barra fixa',
    'costas',
    'ambos',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'advanced',
    true,
    true,
    ARRAY['Pegada pronada um pouco alÃ©m dos ombros.', 'Puxe o peito em direÃ§Ã£o Ã  barra.', 'DesÃ§a atÃ© os braÃ§os quase estenderem.', 'Evite balanÃ§o excessivo.']::text[],
    '{}'::text[],
    'barra-fixa',
    1,
    'barra-fixa',
    'missing'
  ),
(
    'remada-curvada',
    'Remada curvada',
    'costas',
    'academia',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    40,
    1,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'intermediate',
    true,
    true,
    ARRAY['Incline o tronco com coluna neutra.', 'Puxe a barra em direÃ§Ã£o ao umbigo.', 'Aperte as escÃ¡pulas no topo.', 'DesÃ§a com controle sem arredondar as costas.']::text[],
    '{}'::text[],
    'remada-curvada',
    1,
    'remada-curvada',
    'missing'
  ),
(
    'remada-unilateral',
    'Remada unilateral',
    'costas',
    'ambos',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    20,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Apoie um joelho e uma mÃ£o no banco.', 'Puxe o halter atÃ© o quadril.', 'DesÃ§a sem girar o tronco.', 'Troque o lado.']::text[],
    '{}'::text[],
    'remada-unilateral',
    1,
    'remada-unilateral',
    'missing'
  ),
(
    'pulldown',
    'Puxada alta',
    'costas',
    'academia',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    45,
    1,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Sente com o peito aberto e pegada pronada.', 'Puxe a barra atÃ© a clavÃ­cula.', 'Controle a subida.', 'NÃ£o incline demais o tronco para trÃ¡s.']::text[],
    '{}'::text[],
    'pulldown',
    1,
    'pulldown',
    'missing'
  ),
(
    'remada-baixa',
    'Remada baixa',
    'costas',
    'academia',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    40,
    1,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['PÃ©s na plataforma, tronco estÃ¡vel.', 'Puxe o cabo ao umbigo.', 'EscÃ¡pulas juntas no final.', 'Estenda os braÃ§os na volta.']::text[],
    '{}'::text[],
    'remada-baixa',
    1,
    'remada-baixa',
    'missing'
  ),
(
    'pullover',
    'Pullover',
    'costas',
    'academia',
    'costas-pull',
    ARRAY['ombro']::text[],
    'kg',
    16,
    3,
    ARRAY['costas']::text[],
    ARRAY['peito', 'core']::text[],
    'pull',
    'intermediate',
    true,
    true,
    ARRAY['Deite e leve o halter atrÃ¡s da cabeÃ§a com cotovelos moles.', 'Puxe o halter de volta sobre o peito.', 'Sinta o alongamento da grande dorsal.', 'NÃ£o arqueie demais a lombar.']::text[],
    '{}'::text[],
    'pullover',
    1,
    'pullover',
    'missing'
  ),
(
    'barra-fixa-supinada',
    'Barra fixa supinada',
    'costas',
    'ambos',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'advanced',
    true,
    true,
    ARRAY['Pegada supinada na largura dos ombros.', 'Puxe o peito Ã  barra.', 'DesÃ§a controlado.', 'Evite encolher os ombros.']::text[],
    '{}'::text[],
    'barra-fixa-supinada',
    1,
    'barra-fixa-supinada',
    'missing'
  ),
(
    'remada-cavalinho',
    'Remada cavalinho',
    'costas',
    'academia',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    35,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'intermediate',
    true,
    true,
    ARRAY['Peito no apoio da mÃ¡quina.', 'Puxe os cotovelos para trÃ¡s.', 'Aperte as escÃ¡pulas.', 'NÃ£o levante o tronco do apoio.']::text[],
    '{}'::text[],
    'remada-cavalinho',
    1,
    'remada-cavalinho',
    'missing'
  ),
(
    'face-pull',
    'Face pull',
    'costas',
    'academia',
    'costas-row',
    ARRAY['ombro']::text[],
    'kg',
    12,
    2,
    ARRAY['costas']::text[],
    ARRAY['ombros']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Polia alta com corda.', 'Puxe em direÃ§Ã£o ao rosto, cotovelos altos.', 'Gire os punhos para fora no final.', 'Controle a volta.']::text[],
    '{}'::text[],
    'face-pull',
    1,
    'face-pull',
    'missing'
  ),
(
    'remada-halter-peito',
    'Remada com peito apoiado',
    'costas',
    'academia',
    'costas-row',
    ARRAY['punho']::text[],
    'kg',
    16,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Deite de bruÃ§os no banco inclinado.', 'Reme os halteres atÃ© o banco.', 'Aperte as costas no topo.', 'Ãštil para isolar sem sobrecarregar a lombar.']::text[],
    '{}'::text[],
    'remada-halter-peito',
    1,
    'remada-halter-peito',
    'missing'
  ),
(
    'puxada-neutra',
    'Puxada pegada neutra',
    'costas',
    'academia',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    40,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Use o triangulo ou barra paralela.', 'Puxe atÃ© o peito alto.', 'DesÃ§a sem perder a postura.', 'Cotovelos prÃ³ximos ao tronco.']::text[],
    '{}'::text[],
    'puxada-neutra',
    1,
    'puxada-neutra',
    'missing'
  ),
(
    'australian-row',
    'Remada australiana',
    'costas',
    'casa',
    'costas-row',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Deite sob uma barra baixa, corpo rÃ­gido.', 'Puxe o peito atÃ© a barra.', 'DesÃ§a atÃ© os braÃ§os estenderem.', 'Quanto mais horizontal, mais difÃ­cil.']::text[],
    '{}'::text[],
    'australian-row',
    1,
    'australian-row',
    'missing'
  ),
(
    'encolhimento',
    'Encolhimento de ombros',
    'costas',
    'academia',
    'costas-row',
    '{}'::text[],
    'kg',
    40,
    3,
    ARRAY['costas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Barra ou halteres ao lado do corpo.', 'Eleve os ombros em direÃ§Ã£o Ã s orelhas.', 'DesÃ§a com controle.', 'NÃ£o role os ombros para trÃ¡s.']::text[],
    '{}'::text[],
    'encolhimento',
    1,
    'encolhimento',
    'missing'
  ),
(
    'agachamento',
    'Agachamento livre',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho', 'lombar']::text[],
    'kg',
    60,
    1,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'intermediate',
    true,
    true,
    ARRAY['Barra no trapÃ©zio, pÃ©s na largura dos ombros.', 'DesÃ§a com joelhos no rumo dos pÃ©s.', 'Suba empurrando o chÃ£o.', 'Mantenha o peito aberto.']::text[],
    '{}'::text[],
    'agachamento',
    1,
    'agachamento',
    'missing'
  ),
(
    'agachamento-corpo',
    'Agachamento com peso do corpo',
    'pernas',
    'ambos',
    'perna-squat',
    ARRAY['joelho']::text[],
    'corpo',
    0,
    3,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'beginner',
    true,
    true,
    ARRAY['PÃ©s na largura do quadril.', 'DesÃ§a como se fosse sentar.', 'Suba sem jogar os joelhos para dentro.', 'Calcanhares no chÃ£o.']::text[],
    '{}'::text[],
    'agachamento-corpo',
    1,
    'agachamento-corpo',
    'missing'
  ),
(
    'leg-press',
    'Leg press',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    100,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'squat',
    'beginner',
    true,
    true,
    ARRAY['PÃ©s na plataforma na largura do quadril.', 'DesÃ§a atÃ© cerca de 90 graus.', 'Empurre sem travar o joelho de forma brusca.', 'Lombar apoiada.']::text[],
    '{}'::text[],
    'leg-press',
    1,
    'leg-press',
    'missing'
  ),
(
    'afundo',
    'Afundo',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    12,
    1,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'intermediate',
    true,
    true,
    ARRAY['DÃª um passo Ã  frente.', 'DesÃ§a o joelho de trÃ¡s em direÃ§Ã£o ao chÃ£o.', 'Suba sem perder o equilÃ­brio.', 'Tronco alto.']::text[],
    '{}'::text[],
    'afundo',
    1,
    'afundo',
    'missing'
  ),
(
    'terra-romeno',
    'Levantamento terra romeno',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    50,
    1,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'intermediate',
    true,
    true,
    ARRAY['Barra junto Ã s coxas, joelhos moles.', 'Empurre o quadril para trÃ¡s descendo a barra.', 'Sinta o posterior alongar.', 'Volte estendendo o quadril.']::text[],
    '{}'::text[],
    'terra-romeno',
    1,
    'terra-romeno',
    'missing'
  ),
(
    'panturrilha',
    'Panturrilha em pÃ©',
    'pernas',
    'ambos',
    'perna-calf',
    '{}'::text[],
    'kg',
    20,
    1,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['AntepÃ© em um degrau, calcanhar livre.', 'Suba na ponta dos pÃ©s.', 'DesÃ§a alongando a panturrilha.', 'Movimento completo, sem bounce.']::text[],
    '{}'::text[],
    'panturrilha',
    1,
    'panturrilha',
    'missing'
  ),
(
    'agachamento-goblet',
    'Agachamento goblet',
    'pernas',
    'ambos',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    16,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'beginner',
    true,
    true,
    ARRAY['Segure um halter junto ao peito.', 'DesÃ§a entre os joelhos.', 'Suba empurrando o chÃ£o.', 'Cotovelos por dentro das coxas.']::text[],
    '{}'::text[],
    'agachamento-goblet',
    1,
    'agachamento-goblet',
    'missing'
  ),
(
    'agachamento-bulgaro',
    'Agachamento bÃºlgaro',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    12,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'advanced',
    true,
    true,
    ARRAY['PÃ© de trÃ¡s no banco.', 'DesÃ§a o joelho da frente atÃ© 90 graus.', 'Suba sem jogar o tronco Ã  frente demais.', 'Troque o lado.']::text[],
    '{}'::text[],
    'agachamento-bulgaro',
    1,
    'agachamento-bulgaro',
    'missing'
  ),
(
    'stiff',
    'Stiff',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    40,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'intermediate',
    true,
    true,
    ARRAY['Joelhos quase estendidos.', 'DesÃ§a a barra prÃ³xima Ã s pernas.', 'Suba contraindo o glÃºteo.', 'Coluna neutra.']::text[],
    '{}'::text[],
    'stiff',
    1,
    'stiff',
    'missing'
  ),
(
    'cadeira-extensora',
    'Cadeira extensora',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    30,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Ajuste o rolo acima do tornozelo.', 'Estenda os joelhos.', 'DesÃ§a controlado.', 'Evite estalo no travamento.']::text[],
    '{}'::text[],
    'cadeira-extensora',
    1,
    'cadeira-extensora',
    'missing'
  ),
(
    'mesa-flexora',
    'Mesa flexora',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['joelho']::text[],
    'kg',
    25,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Deite de bruÃ§os, rolo na panturrilha.', 'Flexione os calcanhares em direÃ§Ã£o ao glÃºteo.', 'DesÃ§a sem bater o peso.', 'Quadril no banco.']::text[],
    '{}'::text[],
    'mesa-flexora',
    1,
    'mesa-flexora',
    'missing'
  ),
(
    'hack-squat',
    'Hack squat',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    50,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'intermediate',
    true,
    true,
    ARRAY['Costas no encosto, pÃ©s mÃ©dios na plataforma.', 'DesÃ§a atÃ© a profundidade confortÃ¡vel.', 'Empurre pelos calcanhares.', 'Joelhos alinhados.']::text[],
    '{}'::text[],
    'hack-squat',
    1,
    'hack-squat',
    'missing'
  ),
(
    'passo-lateral',
    'Afundo lateral',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    8,
    3,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'intermediate',
    true,
    true,
    ARRAY['Passo largo para o lado.', 'DesÃ§a o quadril sobre a perna da frente.', 'Volte ao centro.', 'PÃ© de apoio firme.']::text[],
    '{}'::text[],
    'passo-lateral',
    1,
    'passo-lateral',
    'missing'
  ),
(
    'elevacao-pelvica',
    'ElevaÃ§Ã£o pÃ©lvica',
    'pernas',
    'ambos',
    'perna-hinge',
    '{}'::text[],
    'kg',
    20,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'beginner',
    true,
    true,
    ARRAY['Ombros no banco, barra sobre o quadril.', 'Empurre o quadril para cima.', 'Aperte o glÃºteo no topo.', 'DesÃ§a com controle.']::text[],
    '{}'::text[],
    'elevacao-pelvica',
    1,
    'elevacao-pelvica',
    'missing'
  ),
(
    'panturrilha-sentado',
    'Panturrilha sentado',
    'pernas',
    'academia',
    'perna-calf',
    '{}'::text[],
    'kg',
    25,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Rolo sobre os joelhos.', 'Suba na ponta dos pÃ©s.', 'DesÃ§a alongando.', 'Pausa curta no topo.']::text[],
    '{}'::text[],
    'panturrilha-sentado',
    1,
    'panturrilha-sentado',
    'missing'
  ),
(
    'agachamento-sumo',
    'Agachamento sumÃ´',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho', 'lombar']::text[],
    'kg',
    50,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'intermediate',
    true,
    true,
    ARRAY['PÃ©s bem abertos, pontas para fora.', 'DesÃ§a o quadril entre os joelhos.', 'Suba contraindo adutores e glÃºteo.', 'Peito alto.']::text[],
    '{}'::text[],
    'agachamento-sumo',
    1,
    'agachamento-sumo',
    'missing'
  ),
(
    'passada-caminhada',
    'Passada caminhando',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    10,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'intermediate',
    true,
    true,
    ARRAY['Afundo contÃ­nuo para frente.', 'Joelho de trÃ¡s desce perto do chÃ£o.', 'Alterne as pernas.', 'Passos estÃ¡veis.']::text[],
    '{}'::text[],
    'passada-caminhada',
    1,
    'passada-caminhada',
    'missing'
  ),
(
    'terra-convencional',
    'Levantamento terra',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar', 'joelho']::text[],
    'kg',
    70,
    1,
    ARRAY['pernas']::text[],
    ARRAY['costas', 'core']::text[],
    'hinge',
    'advanced',
    true,
    true,
    ARRAY['Barra sobre o meio do pÃ©, quadril atrÃ¡s.', 'Puxe a barra raspando as pernas.', 'Trave o quadril no topo.', 'DesÃ§a com a mesma trajetÃ³ria.']::text[],
    '{}'::text[],
    'terra-convencional',
    1,
    'terra-convencional',
    'missing'
  ),
(
    'desenvolvimento',
    'Desenvolvimento militar',
    'ombros',
    'academia',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    30,
    1,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Barra na clavÃ­cula, core firme.', 'Empurre acima da cabeÃ§a.', 'DesÃ§a controlado Ã  clavÃ­cula.', 'NÃ£o jogue a lombar Ã  frente.']::text[],
    '{}'::text[],
    'desenvolvimento',
    1,
    'desenvolvimento',
    'missing'
  ),
(
    'elevacao-lateral',
    'ElevaÃ§Ã£o lateral',
    'ombros',
    'ambos',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    8,
    1,
    ARRAY['ombros']::text[],
    '{}'::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['BraÃ§os levemente flexionados ao lado do corpo.', 'Eleve atÃ© a linha dos ombros.', 'DesÃ§a com controle.', 'NÃ£o encolha o trapÃ©zio.']::text[],
    '{}'::text[],
    'elevacao-lateral',
    1,
    'elevacao-lateral',
    'missing'
  ),
(
    'pike-push',
    'FlexÃ£o pike',
    'ombros',
    'casa',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Quadril alto, corpo em V invertido.', 'DesÃ§a a cabeÃ§a entre as mÃ£os.', 'Empurre de volta.', 'Peso nos ombros, nÃ£o no peito.']::text[],
    '{}'::text[],
    'pike-push',
    1,
    'pike-push',
    'missing'
  ),
(
    'desenvolvimento-halter',
    'Desenvolvimento com halteres',
    'ombros',
    'ambos',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    12,
    1,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Sentado ou em pÃ©, halteres na linha das orelhas.', 'Empurre para cima.', 'DesÃ§a atÃ© os cotovelos a 90 graus.', 'Punhos firmes.']::text[],
    '{}'::text[],
    'desenvolvimento-halter',
    1,
    'desenvolvimento-halter',
    'missing'
  ),
(
    'elevacao-frontal',
    'ElevaÃ§Ã£o frontal',
    'ombros',
    'ambos',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    8,
    2,
    ARRAY['ombros']::text[],
    '{}'::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Halteres Ã  frente das coxas.', 'Eleve atÃ© a linha dos ombros.', 'DesÃ§a lento.', 'NÃ£o balanÃ§e o tronco.']::text[],
    '{}'::text[],
    'elevacao-frontal',
    1,
    'elevacao-frontal',
    'missing'
  ),
(
    'remada-alta',
    'Remada alta',
    'ombros',
    'academia',
    'ombro-raise',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    20,
    3,
    ARRAY['ombros']::text[],
    ARRAY['costas']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Barra na frente das coxas.', 'Puxe atÃ© a clavÃ­cula, cotovelos altos.', 'DesÃ§a controlado.', 'Evite se a articulaÃ§Ã£o do ombro incomodar.']::text[],
    '{}'::text[],
    'remada-alta',
    1,
    'remada-alta',
    'missing'
  ),
(
    'arnold-press',
    'Arnold press',
    'ombros',
    'academia',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    10,
    2,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Comece com palmas Ã  frente do peito.', 'Gire e empurre acima da cabeÃ§a.', 'Volte girando as palmas.', 'Movimento contÃ­nuo.']::text[],
    '{}'::text[],
    'arnold-press',
    1,
    'arnold-press',
    'missing'
  ),
(
    'crucifixo-inverso',
    'Crucifixo inverso',
    'ombros',
    'academia',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    8,
    2,
    ARRAY['ombros']::text[],
    ARRAY['costas']::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Incline o tronco, halteres pendurados.', 'Abra os braÃ§os atÃ© a linha dos ombros.', 'Aperte o deltoide posterior.', 'PescoÃ§o neutro.']::text[],
    '{}'::text[],
    'crucifixo-inverso',
    1,
    'crucifixo-inverso',
    'missing'
  ),
(
    'desenvolvimento-maquina',
    'Desenvolvimento na mÃ¡quina',
    'ombros',
    'academia',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    25,
    2,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Ajuste o assento para as pegadas na linha dos ombros.', 'Empurre para cima.', 'DesÃ§a atÃ© 90 graus.', 'Costas no encosto.']::text[],
    '{}'::text[],
    'desenvolvimento-maquina',
    1,
    'desenvolvimento-maquina',
    'missing'
  ),
(
    'elevacao-lateral-polia',
    'ElevaÃ§Ã£o lateral na polia',
    'ombros',
    'academia',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    6,
    2,
    ARRAY['ombros']::text[],
    '{}'::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Polia baixa cruzada atrÃ¡s do corpo.', 'Eleve o braÃ§o atÃ© a linha do ombro.', 'DesÃ§a sem perder a tensÃ£o.', 'Tronco estÃ¡vel.']::text[],
    '{}'::text[],
    'elevacao-lateral-polia',
    1,
    'elevacao-lateral-polia',
    'missing'
  ),
(
    'handstand-hold',
    'Parada de mÃ£os na parede',
    'ombros',
    'casa',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'min',
    0,
    3,
    ARRAY['ombros']::text[],
    ARRAY['core', 'triceps']::text[],
    'isometric',
    'advanced',
    true,
    true,
    ARRAY['Encontre a parede com os pÃ©s.', 'Trave ombros e core.', 'Respire sem desabar os ombros.', 'DesÃ§a com controle.']::text[],
    '{}'::text[],
    'handstand-hold',
    1,
    'handstand-hold',
    'missing'
  ),
(
    'rosca-direta',
    'Rosca direta',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    20,
    1,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Barra na largura dos ombros, cotovelos junto ao tronco.', 'Flexione atÃ© a barra chegar perto dos ombros.', 'DesÃ§a atÃ© quase estender.', 'NÃ£o jogue o tronco para trÃ¡s.']::text[],
    '{}'::text[],
    'rosca-direta',
    1,
    'rosca-direta',
    'missing'
  ),
(
    'rosca-martelo',
    'Rosca martelo',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    12,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Halteres em pegada neutra.', 'Flexione atÃ© a altura do ombro.', 'DesÃ§a controlado.', 'Cotovelos parados.']::text[],
    '{}'::text[],
    'rosca-martelo',
    1,
    'rosca-martelo',
    'missing'
  ),
(
    'rosca-inclinada',
    'Rosca inclinada',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    10,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['Banco 45â€“60 graus, braÃ§os pendurados.', 'Flexione atÃ© o pico do bÃ­ceps.', 'DesÃ§a alongando.', 'NÃ£o encolha os ombros.']::text[],
    '{}'::text[],
    'rosca-inclinada',
    1,
    'rosca-inclinada',
    'missing'
  ),
(
    'rosca-scott',
    'Rosca scott',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    16,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['BraÃ§os apoiados no banco scott.', 'Flexione atÃ© o pico.', 'DesÃ§a sem estender por completo se o cotovelo incomodar.', 'Tronco colado no apoio.']::text[],
    '{}'::text[],
    'rosca-scott',
    1,
    'rosca-scott',
    'missing'
  ),
(
    'rosca-concentrada',
    'Rosca concentrada',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    10,
    3,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Cotovelo apoiado na coxa interna.', 'Flexione o halter atÃ© o ombro.', 'DesÃ§a lento.', 'Sem balanÃ§o.']::text[],
    '{}'::text[],
    'rosca-concentrada',
    1,
    'rosca-concentrada',
    'missing'
  ),
(
    'rosca-polia',
    'Rosca na polia',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    18,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Polia baixa, barra reta ou W.', 'Flexione mantendo cotovelos fixos.', 'TensÃ£o constante na volta.', 'Postura alta.']::text[],
    '{}'::text[],
    'rosca-polia',
    1,
    'rosca-polia',
    'missing'
  ),
(
    'rosca-banco',
    'Rosca no banco 21',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    12,
    3,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['7 reps da metade inferior, 7 da superior, 7 completas.', 'Cotovelos colados.', 'Carga moderada.', 'Respire a cada bloco.']::text[],
    '{}'::text[],
    'rosca-banco',
    1,
    'rosca-banco',
    'missing'
  ),
(
    'chin-hold',
    'Isometria na barra supinada',
    'biceps',
    'casa',
    'biceps-curl',
    ARRAY['ombro', 'punho']::text[],
    'min',
    0,
    3,
    ARRAY['biceps']::text[],
    ARRAY['costas']::text[],
    'isometric',
    'advanced',
    true,
    true,
    ARRAY['Puxe atÃ© o queixo ficar acima da barra.', 'Segure a posiÃ§Ã£o.', 'DesÃ§a controlado ao final.', 'Ombros longe das orelhas.']::text[],
    '{}'::text[],
    'chin-hold',
    1,
    'chin-hold',
    'missing'
  ),
(
    'triceps-corda',
    'TrÃ­ceps na corda',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    20,
    1,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Cotovelos colados ao tronco.', 'Estenda a corda para baixo abrindo no final.', 'Volte atÃ© 90 graus.', 'NÃ£o abra os cotovelos para o lado.']::text[],
    '{}'::text[],
    'triceps-corda',
    1,
    'triceps-corda',
    'missing'
  ),
(
    'triceps-banco',
    'TrÃ­ceps no banco',
    'triceps',
    'ambos',
    'triceps-ext',
    ARRAY['punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['triceps']::text[],
    ARRAY['ombros']::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['MÃ£os no banco atrÃ¡s do corpo, pÃ©s Ã  frente.', 'DesÃ§a flexionando os cotovelos.', 'Empurre atÃ© estender.', 'Ombros estÃ¡veis.']::text[],
    '{}'::text[],
    'triceps-banco',
    1,
    'triceps-banco',
    'missing'
  ),
(
    'triceps-testa',
    'TrÃ­ceps testa',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    16,
    1,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'intermediate',
    true,
    true,
    ARRAY['Deite, barra acima da testa.', 'Flexione sÃ³ os cotovelos descendo a barra.', 'Estenda de volta.', 'Cotovelos apontando para cima.']::text[],
    '{}'::text[],
    'triceps-testa',
    1,
    'triceps-testa',
    'missing'
  ),
(
    'triceps-frances',
    'TrÃ­ceps francÃªs',
    'triceps',
    'ambos',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    12,
    2,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'intermediate',
    true,
    true,
    ARRAY['Halter atrÃ¡s da cabeÃ§a, cotovelos altos.', 'Estenda acima da cabeÃ§a.', 'DesÃ§a alongando o trÃ­ceps.', 'NÃ£o abra os cotovelos.']::text[],
    '{}'::text[],
    'triceps-frances',
    1,
    'triceps-frances',
    'missing'
  ),
(
    'mergulho-paralelas',
    'Mergulho nas paralelas',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['triceps']::text[],
    ARRAY['peito', 'ombros']::text[],
    'press',
    'advanced',
    true,
    true,
    ARRAY['Tronco mais vertical para Ãªnfase no trÃ­ceps.', 'DesÃ§a atÃ© os ombros confortÃ¡veis.', 'Empurre atÃ© estender.', 'NÃ£o encolha o pescoÃ§o.']::text[],
    '{}'::text[],
    'mergulho-paralelas',
    1,
    'mergulho-paralelas',
    'missing'
  ),
(
    'triceps-coice',
    'TrÃ­ceps coice',
    'triceps',
    'ambos',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    8,
    3,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Tronco inclinado, cotovelo colado.', 'Estenda o halter para trÃ¡s.', 'Volte atÃ© 90 graus.', 'Sem balanÃ§o.']::text[],
    '{}'::text[],
    'triceps-coice',
    1,
    'triceps-coice',
    'missing'
  ),
(
    'triceps-polia-barra',
    'TrÃ­ceps na polia com barra',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    22,
    2,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Barra reta na polia alta.', 'Estenda atÃ© os cotovelos travarem com controle.', 'Volte atÃ© o antebraÃ§o ficar paralelo.', 'Peito aberto.']::text[],
    '{}'::text[],
    'triceps-polia-barra',
    1,
    'triceps-polia-barra',
    'missing'
  ),
(
    'diamond-hold',
    'Isometria flexÃ£o diamante',
    'triceps',
    'casa',
    'triceps-ext',
    ARRAY['ombro', 'punho']::text[],
    'min',
    0,
    3,
    ARRAY['triceps']::text[],
    ARRAY['peito']::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['DesÃ§a atÃ© o meio da flexÃ£o diamante.', 'Segure a posiÃ§Ã£o.', 'Core firme.', 'Suba ao final.']::text[],
    '{}'::text[],
    'diamond-hold',
    1,
    'diamond-hold',
    'missing'
  ),
(
    'prancha',
    'Prancha',
    'core',
    'ambos',
    'core-iso',
    '{}'::text[],
    'min',
    0,
    1,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'beginner',
    true,
    true,
    ARRAY['AntebraÃ§os e pontas dos pÃ©s no chÃ£o.', 'Corpo em linha reta.', 'NÃ£o deixe o quadril cair nem subir demais.', 'Respire sem perder a tensÃ£o.']::text[],
    '{}'::text[],
    'prancha',
    1,
    'prancha',
    'missing'
  ),
(
    'abdominal-remador',
    'Abdominal remador',
    'core',
    'ambos',
    'core-dyn',
    '{}'::text[],
    'corpo',
    0,
    1,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Deite, joelhos e tronco sobem juntos.', 'Estenda na volta sem bater no chÃ£o.', 'Movimento controlado.', 'PescoÃ§o relaxado.']::text[],
    '{}'::text[],
    'abdominal-remador',
    1,
    'abdominal-remador',
    'missing'
  ),
(
    'hollow',
    'Hollow hold',
    'core',
    'ambos',
    'core-iso',
    ARRAY['lombar']::text[],
    'min',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['Lombar colada no chÃ£o.', 'BraÃ§os e pernas levemente elevados.', 'Mantenha a posiÃ§Ã£o.', 'Se a lombar sair, encurte a alavanca.']::text[],
    '{}'::text[],
    'hollow',
    1,
    'hollow',
    'missing'
  ),
(
    'abdominal-infra',
    'ElevaÃ§Ã£o de pernas',
    'core',
    'ambos',
    'core-dyn',
    ARRAY['lombar']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'intermediate',
    true,
    true,
    ARRAY['Deite ou pendure, pernas juntas.', 'Eleve atÃ© 90 graus.', 'DesÃ§a sem arquear a lombar.', 'Movimento lento.']::text[],
    '{}'::text[],
    'abdominal-infra',
    1,
    'abdominal-infra',
    'missing'
  ),
(
    'prancha-lateral',
    'Prancha lateral',
    'core',
    'ambos',
    'core-iso',
    '{}'::text[],
    'min',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['Apoio no antebraÃ§o, corpo de lado.', 'Quadril elevado.', 'Troque o lado.', 'Ombro empilhado sobre o cotovelo.']::text[],
    '{}'::text[],
    'prancha-lateral',
    1,
    'prancha-lateral',
    'missing'
  ),
(
    'ab-wheel',
    'Roda abdominal',
    'core',
    'ambos',
    'core-dyn',
    ARRAY['lombar', 'ombro']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    ARRAY['ombros']::text[],
    'mobility',
    'advanced',
    true,
    true,
    ARRAY['Joelhos no chÃ£o, roda Ã  frente.', 'Role para frente sem deixar a lombar cair.', 'Volte contraindo o abdÃ´men.', 'Amplitude que vocÃª controla.']::text[],
    '{}'::text[],
    'ab-wheel',
    1,
    'ab-wheel',
    'missing'
  ),
(
    'dead-bug',
    'Dead bug',
    'core',
    'casa',
    'core-dyn',
    ARRAY['lombar']::text[],
    'corpo',
    0,
    3,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Deite, braÃ§os e joelhos a 90 graus.', 'Estenda braÃ§o e perna opostos.', 'Volte e alterne.', 'Lombar colada.']::text[],
    '{}'::text[],
    'dead-bug',
    1,
    'dead-bug',
    'missing'
  ),
(
    'mountain-climber',
    'Mountain climber',
    'core',
    'casa',
    'core-dyn',
    ARRAY['joelho', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    ARRAY['cardio']::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Prancha alta.', 'Alterne os joelhos em direÃ§Ã£o ao peito.', 'Quadril estÃ¡vel.', 'Ritmo constante.']::text[],
    '{}'::text[],
    'mountain-climber',
    1,
    'mountain-climber',
    'missing'
  ),
(
    'pallof',
    'Pallof press',
    'core',
    'academia',
    'core-iso',
    '{}'::text[],
    'kg',
    10,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['De lado para a polia, cabo no peito.', 'Empurre os braÃ§os Ã  frente resistindo Ã  rotaÃ§Ã£o.', 'Volte ao peito.', 'Quadril travado.']::text[],
    '{}'::text[],
    'pallof',
    1,
    'pallof',
    'missing'
  ),
(
    'crunch',
    'Abdominal crunch',
    'core',
    'casa',
    'core-dyn',
    '{}'::text[],
    'corpo',
    0,
    3,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Deite, joelhos dobrados.', 'Eleve as escÃ¡pulas do chÃ£o.', 'DesÃ§a sem relaxar por completo.', 'NÃ£o puxe o pescoÃ§o.']::text[],
    '{}'::text[],
    'crunch',
    1,
    'crunch',
    'missing'
  ),
(
    'farmers-carry',
    'Farmer walk',
    'core',
    'academia',
    'core-iso',
    ARRAY['punho']::text[],
    'kg',
    24,
    2,
    ARRAY['core']::text[],
    ARRAY['ombros']::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['Halteres pesados ao lado do corpo.', 'Caminhe com tronco alto.', 'Passos curtos e estÃ¡veis.', 'Ombros longe das orelhas.']::text[],
    '{}'::text[],
    'farmers-carry',
    1,
    'farmers-carry',
    'missing'
  ),
(
    'russian-twist',
    'Russian twist',
    'core',
    'ambos',
    'core-dyn',
    '{}'::text[],
    'kg',
    6,
    3,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'intermediate',
    true,
    true,
    ARRAY['Sentado, tronco recuado, pÃ©s elevados se possÃ­vel.', 'Gire o implemento de um lado ao outro.', 'Respire a cada giro.', 'NÃ£o arredonde demais a lombar.']::text[],
    '{}'::text[],
    'russian-twist',
    1,
    'russian-twist',
    'missing'
  ),
(
    'corrida',
    'Corrida contÃ­nua',
    'cardio',
    'ambos',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'min',
    0,
    1,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Ritmo conversÃ¡vel.', 'Passada leve, tronco alto.', 'Respire pelo nariz e boca conforme precisar.', 'Termine com desaquecimento.']::text[],
    '{}'::text[],
    'corrida',
    1,
    'corrida',
    'missing'
  ),
(
    'hiit-bike',
    'HIIT na bike',
    'cardio',
    'academia',
    'cardio-hiit',
    '{}'::text[],
    'min',
    0,
    1,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Alterne sprints curtos e recuperaÃ§Ã£o.', 'Postura firme no selim.', 'NÃ£o prenda a respiraÃ§Ã£o.', 'Ajuste a carga para completar os intervalos.']::text[],
    '{}'::text[],
    'hiit-bike',
    1,
    'hiit-bike',
    'missing'
  ),
(
    'burpee',
    'Burpee',
    'cardio',
    'ambos',
    'cardio-hiit',
    ARRAY['joelho', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['peito', 'core']::text[],
    'cardio',
    'advanced',
    true,
    true,
    ARRAY['Agache, mÃ£os no chÃ£o, jogue os pÃ©s para trÃ¡s.', 'FlexÃ£o opcional, volte os pÃ©s e salte.', 'Ritmo sustentÃ¡vel.', 'Aterrisse macio.']::text[],
    '{}'::text[],
    'burpee',
    1,
    'burpee',
    'missing'
  ),
(
    'pular-corda',
    'Pular corda',
    'cardio',
    'ambos',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Saltos baixos na ponta dos pÃ©s.', 'Punhos giram a corda, nÃ£o os braÃ§os inteiros.', 'Ritmo constante.', 'Joelhos moles.']::text[],
    '{}'::text[],
    'pular-corda',
    1,
    'pular-corda',
    'missing'
  ),
(
    'remo-ergometro',
    'Remo ergÃ´metro',
    'cardio',
    'academia',
    'cardio-steady',
    ARRAY['joelho', 'lombar']::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['costas']::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Pernas, quadril e braÃ§os nessa ordem.', 'Volta reversa: braÃ§os, quadril, pernas.', 'CadÃªncia estÃ¡vel.', 'NÃ£o arredonde as costas.']::text[],
    '{}'::text[],
    'remo-ergometro',
    1,
    'remo-ergometro',
    'missing'
  ),
(
    'eliptico',
    'ElÃ­ptico',
    'cardio',
    'academia',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'min',
    0,
    3,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Postura alta, impulso nos pÃ©s e braÃ§os.', 'CadÃªncia constante.', 'NÃ£o trave os joelhos.', 'Use para baixo impacto.']::text[],
    '{}'::text[],
    'eliptico',
    1,
    'eliptico',
    'missing'
  ),
(
    'jumping-jack',
    'Polichinelo',
    'cardio',
    'casa',
    'cardio-hiit',
    ARRAY['joelho']::text[],
    'corpo',
    0,
    3,
    ARRAY['cardio']::text[],
    ARRAY['ombros']::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Salte abrindo pÃ©s e braÃ§os.', 'Volte ao centro.', 'Ritmo constante.', 'Aterrisse macio.']::text[],
    '{}'::text[],
    'jumping-jack',
    1,
    'jumping-jack',
    'missing'
  ),
(
    'battle-rope',
    'Corda naval',
    'cardio',
    'academia',
    'cardio-hiit',
    ARRAY['ombro']::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['core']::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Joelhos moles, tronco estÃ¡vel.', 'Ondas alternadas com as cordas.', 'Intervalos curtos.', 'NÃ£o encolha os ombros.']::text[],
    '{}'::text[],
    'battle-rope',
    1,
    'battle-rope',
    'missing'
  ),
(
    'subida-caixa',
    'Subida na caixa',
    'cardio',
    'ambos',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'corpo',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['pernas']::text[],
    'lunge',
    'beginner',
    true,
    true,
    ARRAY['Pise com o pÃ© inteiro na caixa.', 'Suba estendendo o quadril.', 'DesÃ§a com controle.', 'Alterne as pernas.']::text[],
    '{}'::text[],
    'subida-caixa',
    1,
    'subida-caixa',
    'missing'
  ),
(
    'assalto-bike',
    'Assault bike',
    'cardio',
    'academia',
    'cardio-hiit',
    '{}'::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['ombros']::text[],
    'cardio',
    'advanced',
    true,
    true,
    ARRAY['Empurre e puxe os braÃ§os junto com as pernas.', 'Sprints curtos.', 'Recupere sem parar de pedalar.', 'Tronco estÃ¡vel.']::text[],
    '{}'::text[],
    'assalto-bike',
    1,
    'assalto-bike',
    'missing'
  ),
(
    'crucifixo-polia-baixa',
    'Crucifixo na polia baixa',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    10,
    3,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Polias baixas, passo Ã  frente.', 'Suba os cabos em arco atÃ© a frente do peito.', 'DesÃ§a alongando.', 'Cotovelos moles.']::text[],
    '{}'::text[],
    'crucifixo-polia-baixa',
    1,
    'crucifixo-polia-baixa',
    'missing'
  ),
(
    'good-morning',
    'Good morning',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    30,
    3,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'advanced',
    true,
    true,
    ARRAY['Barra no trapÃ©zio, joelhos moles.', 'Incline o tronco empurrando o quadril para trÃ¡s.', 'Volte estendendo o quadril.', 'Carga conservadora.']::text[],
    '{}'::text[],
    'good-morning',
    1,
    'good-morning',
    'missing'
  ),
(
    'adutora',
    'Cadeira adutora',
    'pernas',
    'academia',
    'perna-squat',
    '{}'::text[],
    'kg',
    30,
    3,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Joelhos nas almofadas da mÃ¡quina.', 'Feche as pernas contra a resistÃªncia.', 'Abra com controle.', 'Tronco apoiado.']::text[],
    '{}'::text[],
    'adutora',
    1,
    'adutora',
    'missing'
  ),
(
    'abdutora',
    'Cadeira abdutora',
    'pernas',
    'academia',
    'perna-squat',
    '{}'::text[],
    'kg',
    30,
    3,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Joelhos nas almofadas.', 'Abra as pernas contra a resistÃªncia.', 'Feche controlado.', 'NÃ£o arqueie a lombar.']::text[],
    '{}'::text[],
    'abdutora',
    1,
    'abdutora',
    'missing'
  ),
(
    'rosca-inversa',
    'Rosca inversa',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    12,
    3,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['Pegada pronada na barra.', 'Flexione atÃ© a barra chegar perto dos ombros.', 'DesÃ§a lento.', 'Punhos firmes.']::text[],
    '{}'::text[],
    'rosca-inversa',
    1,
    'rosca-inversa',
    'missing'
  ),
(
    'hanging-knee-raise',
    'ElevaÃ§Ã£o de joelhos na barra',
    'core',
    'ambos',
    'core-dyn',
    ARRAY['ombro']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'intermediate',
    true,
    true,
    ARRAY['Pendure na barra, ombros ativos.', 'Eleve os joelhos ao peito.', 'DesÃ§a sem balanÃ§o excessivo.', 'NÃ£o encolha o pescoÃ§o.']::text[],
    '{}'::text[],
    'hanging-knee-raise',
    1,
    'hanging-knee-raise',
    'missing'
  ),
(
    'kettlebell-swing',
    'Swing com kettlebell',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    16,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core', 'ombros']::text[],
    'hinge',
    'intermediate',
    true,
    true,
    ARRAY['Hinge, kettlebell entre as pernas.', 'Estenda o quadril projetando o peso Ã  frente.', 'Deixe o peso flutuar atÃ© a linha dos ombros.', 'NÃ£o levante com os braÃ§os.']::text[],
    '{}'::text[],
    'kettlebell-swing',
    1,
    'kettlebell-swing',
    'missing'
  ),
(
    'ski-erg',
    'SkiErg',
    'cardio',
    'academia',
    'cardio-hiit',
    ARRAY['ombro']::text[],
    'min',
    0,
    3,
    ARRAY['cardio']::text[],
    ARRAY['core']::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Puxe as alÃ§as de cima para baixo com o quadril.', 'Estenda o quadril no final da puxada.', 'Recupere os braÃ§os alto.', 'CadÃªncia rÃ­tmica.']::text[],
    '{}'::text[],
    'ski-erg',
    1,
    'ski-erg',
    'missing'
  )
ON CONFLICT (id) DO NOTHING;


INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20261010120000', '20261010120000_fase3_unified_exercise_catalog')
ON CONFLICT (version) DO NOTHING;


-- ========== 20261011120000_fase5_learning_behavior_convergence.sql ==========
-- Fase 5 Learning/Behavior convergence â€” stable experiment upserts
-- Additive unique on (user_id, client_id). No new tables.

UPDATE public.behavior_experiments
SET client_id = id::text
WHERE client_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS behavior_experiments_user_client_uidx
  ON public.behavior_experiments (user_id, client_id)
  WHERE client_id IS NOT NULL;


INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20261011120000', '20261011120000_fase5_learning_behavior_convergence')
ON CONFLICT (version) DO NOTHING;


-- ========== 20261012120000_fase6_media_governance.sql ==========
-- Fase 6 Soldiers Media Governance
-- Additive: status machine, variants/regions, checksums, CMS authorization.
-- No new media tables. Does not generate 800 assets.

ALTER TABLE public.soldiers_media
  ADD COLUMN IF NOT EXISTS variant text NOT NULL DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS region text NOT NULL DEFAULT 'global',
  ADD COLUMN IF NOT EXISTS prompt text,
  ADD COLUMN IF NOT EXISTS animation_spec jsonb,
  ADD COLUMN IF NOT EXISTS checksums jsonb;

DO $$
DECLARE
  cname text;
BEGIN
  FOR cname IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.soldiers_media'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%status%'
  LOOP
    EXECUTE format('ALTER TABLE public.soldiers_media DROP CONSTRAINT %I', cname);
  END LOOP;
END $$;

UPDATE public.soldiers_media
SET status = 'draft'
WHERE status = 'pending';

ALTER TABLE public.soldiers_media
  ADD CONSTRAINT soldiers_media_status_check
  CHECK (
    status IN ('draft', 'generated', 'qa', 'approved', 'published', 'rejected', 'archived')
  );

ALTER TABLE public.soldiers_media DROP CONSTRAINT IF EXISTS soldiers_media_pkey;
ALTER TABLE public.soldiers_media
  ADD PRIMARY KEY (kind, entity_id, version, variant, region);

CREATE UNIQUE INDEX IF NOT EXISTS soldiers_media_one_published_default_uidx
  ON public.soldiers_media (kind, entity_id, region)
  WHERE status = 'published' AND variant = 'default';

CREATE INDEX IF NOT EXISTS soldiers_media_kind_entity_status_idx
  ON public.soldiers_media (kind, entity_id, status);

COMMENT ON COLUMN public.soldiers_media.variant IS
  'A/B visual slot. Resolver v1 uses default only.';
COMMENT ON COLUMN public.soldiers_media.region IS
  'Regional variant. Resolver v1 uses global only.';
COMMENT ON COLUMN public.soldiers_media.checksums IS
  'sha256 hex per asset key: poster, thumbnail, webm, mp4, gif.';

ALTER TABLE public.cms_overrides
  ADD COLUMN IF NOT EXISTS authorized boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS authorized_at timestamptz,
  ADD COLUMN IF NOT EXISTS authorized_by text;

COMMENT ON COLUMN public.cms_overrides.authorized IS
  'When true AND URL is Soldiers-owned, CMS may fill a production gap (never beats published Soldiers media).';

ALTER TABLE public.admin_audit_log DROP CONSTRAINT IF EXISTS admin_audit_log_action_check;
ALTER TABLE public.admin_audit_log
  ADD CONSTRAINT admin_audit_log_action_check
  CHECK (
    action IN (
      'cms_save',
      'entitlement_resync',
      'entitlement_grant',
      'entitlement_revoke',
      'user_suspend',
      'user_ban',
      'user_unsuspend',
      'catalog_exercise_save',
      'catalog_challenge_save',
      'training_rules_save',
      'content_item_save',
      'content_item_delete',
      'content_report_resolve',
      'activity_hide',
      'activity_unhide',
      'comment_hide',
      'comment_unhide',
      'shopify_customers_import',
      'media_status_change'
    )
  );


INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20261012120000', '20261012120000_fase6_media_governance')
ON CONFLICT (version) DO NOTHING;


-- ========== 20261013120000_fase7_catalog_scale.sql ==========
-- Fase 7 â€” Catalog Scale
-- Additive food_items columns for EAN lookup and internal source versioning.
-- No new food_catalog tables. RLS unchanged.

ALTER TABLE public.food_items
  ADD COLUMN IF NOT EXISTS ean text,
  ADD COLUMN IF NOT EXISTS source_version text;

CREATE UNIQUE INDEX IF NOT EXISTS food_items_ean_unique
  ON public.food_items (ean)
  WHERE ean IS NOT NULL AND btrim(ean) <> '';


INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20261013120000', '20261013120000_fase7_catalog_scale')
ON CONFLICT (version) DO NOTHING;


-- ========== 20261014120000_fase8_athlete_network_content_os.sql ==========
-- Fase 8 â€” Athlete Network + Content OS
-- activities = physical SoT (not activity_events feed).
-- Content OS extends content_items; CMS tables service_role only.
-- RLS unchanged pattern: revoke anon/authenticated, grant service_role.

-- ---------------------------------------------------------------------------
-- Activities
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.activities (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  source text NOT NULL CHECK (source IN ('app', 'strava', 'garmin', 'wearable', 'manual')),
  external_id text,
  type text NOT NULL CHECK (
    type IN ('strength', 'run', 'walk', 'football', 'cycling', 'cardio', 'challenge', 'manual')
  ),
  started_at timestamptz NOT NULL,
  duration_sec integer,
  distance_m numeric,
  calories numeric,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  proof_status text NOT NULL DEFAULT 'self_reported',
  device text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS activities_user_source_external_uid
  ON public.activities (user_id, source, external_id)
  WHERE external_id IS NOT NULL AND btrim(external_id) <> '';

CREATE INDEX IF NOT EXISTS activities_user_started_idx
  ON public.activities (user_id, started_at DESC);

ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.activities FROM anon, authenticated;
GRANT ALL ON TABLE public.activities TO service_role;

-- ---------------------------------------------------------------------------
-- Content OS â€” experts / collections / programs / progress
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.experts (
  id text PRIMARY KEY,
  name text NOT NULL,
  bio text NOT NULL DEFAULT '',
  specialty text NOT NULL DEFAULT '',
  photo_media_id text,
  social jsonb NOT NULL DEFAULT '{}'::jsonb,
  verified boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  updated_by text NOT NULL DEFAULT 'pin-admin',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.experts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.experts FROM anon, authenticated;
GRANT ALL ON TABLE public.experts TO service_role;

CREATE TABLE IF NOT EXISTS public.content_collections (
  id text PRIMARY KEY,
  title text NOT NULL,
  kind text NOT NULL DEFAULT 'education',
  expert_id text REFERENCES public.experts(id) ON DELETE SET NULL,
  cover_media_id text,
  published boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  updated_by text NOT NULL DEFAULT 'pin-admin',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.content_collections ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.content_collections FROM anon, authenticated;
GRANT ALL ON TABLE public.content_collections TO service_role;

CREATE TABLE IF NOT EXISTS public.programs (
  id text PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  goal text,
  level text,
  duration_weeks integer NOT NULL DEFAULT 4,
  sessions_per_week integer NOT NULL DEFAULT 3,
  expert_ids text[] NOT NULL DEFAULT '{}'::text[],
  published boolean NOT NULL DEFAULT false,
  cover_media_id text,
  publish_at timestamptz,
  updated_by text NOT NULL DEFAULT 'pin-admin',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.programs FROM anon, authenticated;
GRANT ALL ON TABLE public.programs TO service_role;

CREATE TABLE IF NOT EXISTS public.program_sessions (
  id text PRIMARY KEY,
  program_id text NOT NULL REFERENCES public.programs(id) ON DELETE CASCADE,
  week integer NOT NULL DEFAULT 1,
  day integer NOT NULL DEFAULT 1,
  training_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  nutrition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  recovery_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  content_item_id text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS program_sessions_program_idx
  ON public.program_sessions (program_id, week, day);

ALTER TABLE public.program_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.program_sessions FROM anon, authenticated;
GRANT ALL ON TABLE public.program_sessions TO service_role;

CREATE TABLE IF NOT EXISTS public.content_progress (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  content_id text NOT NULL,
  completed_at timestamptz,
  completion_percent integer NOT NULL DEFAULT 0,
  saved boolean NOT NULL DEFAULT false,
  dismissed boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, content_id)
);

ALTER TABLE public.content_progress ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.content_progress FROM anon, authenticated;
GRANT ALL ON TABLE public.content_progress TO service_role;

-- ---------------------------------------------------------------------------
-- content_items extensions
-- ---------------------------------------------------------------------------
ALTER TABLE public.content_items DROP CONSTRAINT IF EXISTS content_items_kind_check;
ALTER TABLE public.content_items
  ADD CONSTRAINT content_items_kind_check CHECK (
    kind IN ('article', 'tip', 'technique', 'nutrition', 'recovery', 'motivation', 'video', 'education')
  );

ALTER TABLE public.content_items ADD COLUMN IF NOT EXISTS expert_id text;
ALTER TABLE public.content_items ADD COLUMN IF NOT EXISTS collection_id text;
ALTER TABLE public.content_items ADD COLUMN IF NOT EXISTS media_id text;
ALTER TABLE public.content_items ADD COLUMN IF NOT EXISTS publish_at timestamptz;
ALTER TABLE public.content_items ADD COLUMN IF NOT EXISTS unpublish_at timestamptz;
ALTER TABLE public.content_items ADD COLUMN IF NOT EXISTS visible boolean NOT NULL DEFAULT true;

-- ---------------------------------------------------------------------------
-- Soldiers media kinds for expert / program covers (draft packages)
-- ---------------------------------------------------------------------------
ALTER TABLE public.soldiers_media DROP CONSTRAINT IF EXISTS soldiers_media_kind_check;
ALTER TABLE public.soldiers_media
  ADD CONSTRAINT soldiers_media_kind_check CHECK (
    kind IN ('exercise', 'meal', 'product', 'hub', 'challenge', 'brand', 'howto', 'expert', 'program')
  );


INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20261014120000', '20261014120000_fase8_athlete_network_content_os')
ON CONFLICT (version) DO NOTHING;

