#!/usr/bin/env node
/**
 * Import TACO-like JSON into SQL seed (Phase 2).
 *
 * Usage:
 *   node scripts/import-taco.mjs path/to/foods.json [--out supabase/seed-taco.sql]
 *
 * Expected JSON (array):
 * [{
 *   "id": "string",
 *   "name": "string",
 *   "category": "string",
 *   "source": "taco"|"imported"|"internal",
 *   "licenseVerified": true,   // REQUIRED — script refuses otherwise
 *   "synonyms": ["..."],
 *   "per100g": { "energyKcal": 0, "proteinG": 0, "carbG": 0, "fatG": 0, "fiberG": 0 },
 *   "servings": [{ "id": "s-100g", "label": "100 g", "grams": 100, "isDefault": true }]
 * }]
 *
 * Does NOT ship licensed TACO data. Provide your own verified dump.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const args = process.argv.slice(2);
const inputPath = args.find((a) => !a.startsWith("--"));
const outIdx = args.indexOf("--out");
const outPath = outIdx >= 0 ? args[outIdx + 1] : "supabase/seed-taco-import.sql";

if (!inputPath) {
  console.error("Usage: node scripts/import-taco.mjs <foods.json> [--out file.sql]");
  process.exit(1);
}

const raw = JSON.parse(readFileSync(resolve(inputPath), "utf8"));
if (!Array.isArray(raw)) {
  console.error("JSON must be an array of food objects");
  process.exit(1);
}

const ALLOWED_SOURCES = new Set(["taco", "imported", "internal"]);
const seenIds = new Set();
const errors = [];
const foods = [];

for (const [i, row] of raw.entries()) {
  const id = String(row?.id ?? "").trim();
  const name = String(row?.name ?? "").trim();
  if (!id || !name) {
    errors.push(`[${i}] missing id/name`);
    continue;
  }
  if (seenIds.has(id)) {
    errors.push(`[${i}] duplicate id: ${id}`);
    continue;
  }
  seenIds.add(id);

  if (row.licenseVerified !== true) {
    errors.push(`[${i}] ${id}: licenseVerified must be true`);
    continue;
  }

  const source = String(row.source ?? "imported");
  if (!ALLOWED_SOURCES.has(source)) {
    errors.push(`[${i}] ${id}: invalid source ${source}`);
    continue;
  }

  const p = row.per100g ?? {};
  for (const key of ["energyKcal", "proteinG", "carbG", "fatG"]) {
    if (typeof p[key] !== "number" || Number.isNaN(p[key])) {
      errors.push(`[${i}] ${id}: per100g.${key} must be number`);
    }
  }

  const servings = Array.isArray(row.servings) ? row.servings : [];
  for (const s of servings) {
    if (!s.label || typeof s.grams !== "number" || s.grams <= 0) {
      errors.push(`[${i}] ${id}: invalid serving`);
    }
  }

  foods.push({
    id,
    name,
    category: String(row.category ?? "outros"),
    brand: row.brand ? String(row.brand) : null,
    source,
    servingReference: String(row.servingReference ?? servings.find((s) => s.isDefault)?.id ?? "s-100g"),
    confidence: typeof row.confidence === "number" ? row.confidence : 0.8,
    synonyms: Array.isArray(row.synonyms) ? row.synonyms.map(String) : [],
    per100g: {
      energyKcal: Number(p.energyKcal),
      proteinG: Number(p.proteinG),
      carbG: Number(p.carbG),
      fatG: Number(p.fatG),
      ...(p.fiberG != null ? { fiberG: Number(p.fiberG) } : {}),
      ...(p.sodiumMg != null ? { sodiumMg: Number(p.sodiumMg) } : {}),
    },
    servings: servings.length
      ? servings
      : [{ id: "s-100g", label: "100 g", grams: 100, isDefault: true }],
  });
}

if (errors.length) {
  console.error(`Validation failed (${errors.length} issues):`);
  for (const e of errors.slice(0, 40)) console.error(" -", e);
  if (errors.length > 40) console.error(` ... and ${errors.length - 40} more`);
  process.exit(1);
}

function esc(s) {
  return String(s).replace(/'/g, "''");
}

function sqlArray(arr) {
  if (!arr.length) return "'{}'";
  return `ARRAY[${arr.map((x) => `'${esc(x)}'`).join(",")}]`;
}

const lines = [
  "-- Generated by scripts/import-taco.mjs — review before applying",
  `-- Foods: ${foods.length}`,
  "",
];

for (const f of foods) {
  lines.push(
    `INSERT INTO public.food_items (id, name, brand, category, source, serving_reference, confidence, synonyms, per100g)`,
  );
  lines.push(
    `VALUES ('${esc(f.id)}', '${esc(f.name)}', ${f.brand ? `'${esc(f.brand)}'` : "NULL"}, '${esc(f.category)}', '${f.source}', '${esc(f.servingReference)}', ${f.confidence}, ${sqlArray(f.synonyms)}, '${JSON.stringify(f.per100g)}'::jsonb)`,
  );
  lines.push(`ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, per100g = EXCLUDED.per100g, updated_at = now();`);
  lines.push("");

  for (const s of f.servings) {
    const sid = `${f.id}:${s.id ?? s.label}`;
    lines.push(
      `INSERT INTO public.food_servings (id, food_id, label, grams_equivalent, is_default) VALUES ('${esc(sid)}', '${esc(f.id)}', '${esc(s.label)}', ${Number(s.grams)}, ${s.isDefault ? "true" : "false"}) ON CONFLICT (id) DO UPDATE SET grams_equivalent = EXCLUDED.grams_equivalent;`,
    );
  }

  for (const [key, unit] of [
    ["energyKcal", "kcal"],
    ["proteinG", "g"],
    ["carbG", "g"],
    ["fatG", "g"],
    ["fiberG", "g"],
    ["sodiumMg", "mg"],
  ]) {
    const val = f.per100g[key];
    if (val == null) continue;
    lines.push(
      `INSERT INTO public.food_nutrients (food_id, nutrient_key, value, unit, source, kind, confidence) VALUES ('${esc(f.id)}', '${key}', ${val}, '${unit}', '${f.source}', 'observed', ${f.confidence}) ON CONFLICT (food_id, nutrient_key, source) DO UPDATE SET value = EXCLUDED.value;`,
    );
  }
  lines.push("");
}

if (foods.length) {
  lines.push(
    "INSERT INTO public.catalog_settings (id, taco_license_verified, updated_at) VALUES ('default', true, now()) ON CONFLICT (id) DO UPDATE SET taco_license_verified = true, updated_at = now();",
  );
  lines.push("");
}

writeFileSync(resolve(outPath), lines.join("\n"), "utf8");
console.log(`OK: ${foods.length} foods → ${outPath}`);
