/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as HubsRouteImport } from './routes/hubs'
import { Route as NutricaoRouteImport } from './routes/nutricao'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SuplementosRouteImport } from './routes/suplementos'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ConteudoIndexRouteImport } from './routes/conteudo.index'
import { Route as ConteudoIdRouteImport } from './routes/conteudo.$id'
import { Route as GovernanceIndexRouteImport } from './routes/governance.index'
import { Route as GovernanceAgentsRouteImport } from './routes/governance.agents'
import { Route as GovernanceCostRouteImport } from './routes/governance.cost'
import { Route as GovernanceDecisionsRouteImport } from './routes/governance.decisions'
import { Route as GovernanceEvaluationRouteImport } from './routes/governance.evaluation'
import { Route as GovernanceOverviewRouteImport } from './routes/governance.overview'
import { Route as GovernanceRagRouteImport } from './routes/governance.rag'
import { Route as GovernanceRunsRouteImport } from './routes/governance.runs'
import { Route as GovernanceSafetyRouteImport } from './routes/governance.safety'
import { Route as HubsSlugRouteImport } from './routes/hubs.$slug'
import { Route as ProgressoIndexRouteImport } from './routes/progresso.index'
import { Route as ProgressoCorpoRouteImport } from './routes/progresso.corpo'
import { Route as ProgressoResumoRouteImport } from './routes/progresso.resumo'
import { Route as SocialIndexRouteImport } from './routes/social.index'
import { Route as SocialUserIdRouteImport } from './routes/social.$userId'
import { Route as SocialSeguidoresRouteImport } from './routes/social.seguidores'
import { Route as TreinoIndexRouteImport } from './routes/treino.index'
import { Route as WearablesCallbackRouteImport } from './routes/wearables.callback'
import { Route as ApiCronDailyPushesRouteImport } from './routes/api/cron.daily-pushes'
import { Route as ApiShopifyWebhookRouteImport } from './routes/api/shopify.webhook'
import { Route as TreinoExercicioIdRouteImport } from './routes/treino.exercicio.$id'
import { Route as TreinoHistoricoSessionIdRouteImport } from './routes/treino.historico.$sessionId'
import { Route as TreinoSessaoIdRouteImport } from './routes/treino.sessao.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoRoute = NutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SuplementosRoute = SuplementosRouteImport.update({
  id: '/suplementos',
  path: '/suplementos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoIndexRoute = ConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoIdRoute = ConteudoIdRouteImport.update({
  id: '/conteudo/$id',
  path: '/conteudo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceAgentsRoute = GovernanceAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceCostRoute = GovernanceCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceDecisionsRoute = GovernanceDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceEvaluationRoute = GovernanceEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceOverviewRoute = GovernanceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceRagRoute = GovernanceRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceRunsRoute = GovernanceRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceSafetyRoute = GovernanceSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => GovernanceRoute,
} as any)
const HubsSlugRoute = HubsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HubsRoute,
} as any)
const ProgressoIndexRoute = ProgressoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgressoRoute,
} as any)
const ProgressoCorpoRoute = ProgressoCorpoRouteImport.update({
  id: '/corpo',
  path: '/corpo',
  getParentRoute: () => ProgressoRoute,
} as any)
const ProgressoResumoRoute = ProgressoResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => ProgressoRoute,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SocialRoute,
} as any)
const SocialUserIdRoute = SocialUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => SocialRoute,
} as any)
const SocialSeguidoresRoute = SocialSeguidoresRouteImport.update({
  id: '/seguidores',
  path: '/seguidores',
  getParentRoute: () => SocialRoute,
} as any)
const TreinoIndexRoute = TreinoIndexRouteImport.update({
  id: '/treino/',
  path: '/treino/',
  getParentRoute: () => rootRouteImport,
} as any)
const WearablesCallbackRoute = WearablesCallbackRouteImport.update({
  id: '/wearables/callback',
  path: '/wearables/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyPushesRoute = ApiCronDailyPushesRouteImport.update({
  id: '/api/cron/daily-pushes',
  path: '/api/cron/daily-pushes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyWebhookRoute = ApiShopifyWebhookRouteImport.update({
  id: '/api/shopify/webhook',
  path: '/api/shopify/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoExercicioIdRoute = TreinoExercicioIdRouteImport.update({
  id: '/treino/exercicio/$id',
  path: '/treino/exercicio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoHistoricoSessionIdRoute =
  TreinoHistoricoSessionIdRouteImport.update({
    id: '/treino/historico/$sessionId',
    path: '/treino/historico/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TreinoSessaoIdRoute = TreinoSessaoIdRouteImport.update({
  id: '/treino/sessao/$id',
  path: '/treino/sessao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/clubes': typeof ClubesRoute
  '/coach': typeof CoachRoute
  '/desafios': typeof DesafiosRoute
  '/entrar': typeof EntrarRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/hubs': typeof HubsRouteWithChildren
  '/nutricao': typeof NutricaoRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRouteWithChildren
  '/social': typeof SocialRouteWithChildren
  '/suplementos': typeof SuplementosRoute
  '/termos': typeof TermosRoute
  '/welcome': typeof WelcomeRoute
  '/conteudo/$id': typeof ConteudoIdRoute
  '/governance/agents': typeof GovernanceAgentsRoute
  '/governance/cost': typeof GovernanceCostRoute
  '/governance/decisions': typeof GovernanceDecisionsRoute
  '/governance/evaluation': typeof GovernanceEvaluationRoute
  '/governance/overview': typeof GovernanceOverviewRoute
  '/governance/rag': typeof GovernanceRagRoute
  '/governance/runs': typeof GovernanceRunsRoute
  '/governance/safety': typeof GovernanceSafetyRoute
  '/hubs/$slug': typeof HubsSlugRoute
  '/progresso/corpo': typeof ProgressoCorpoRoute
  '/progresso/resumo': typeof ProgressoResumoRoute
  '/social/$userId': typeof SocialUserIdRoute
  '/social/seguidores': typeof SocialSeguidoresRoute
  '/wearables/callback': typeof WearablesCallbackRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/progresso/': typeof ProgressoIndexRoute
  '/social/': typeof SocialIndexRoute
  '/treino/': typeof TreinoIndexRoute
  '/api/cron/daily-pushes': typeof ApiCronDailyPushesRoute
  '/api/shopify/webhook': typeof ApiShopifyWebhookRoute
  '/treino/exercicio/$id': typeof TreinoExercicioIdRoute
  '/treino/historico/$sessionId': typeof TreinoHistoricoSessionIdRoute
  '/treino/sessao/$id': typeof TreinoSessaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/clubes': typeof ClubesRoute
  '/coach': typeof CoachRoute
  '/desafios': typeof DesafiosRoute
  '/entrar': typeof EntrarRoute
  '/hubs': typeof HubsRouteWithChildren
  '/nutricao': typeof NutricaoRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/suplementos': typeof SuplementosRoute
  '/termos': typeof TermosRoute
  '/welcome': typeof WelcomeRoute
  '/conteudo/$id': typeof ConteudoIdRoute
  '/governance/agents': typeof GovernanceAgentsRoute
  '/governance/cost': typeof GovernanceCostRoute
  '/governance/decisions': typeof GovernanceDecisionsRoute
  '/governance/evaluation': typeof GovernanceEvaluationRoute
  '/governance/overview': typeof GovernanceOverviewRoute
  '/governance/rag': typeof GovernanceRagRoute
  '/governance/runs': typeof GovernanceRunsRoute
  '/governance/safety': typeof GovernanceSafetyRoute
  '/hubs/$slug': typeof HubsSlugRoute
  '/progresso/corpo': typeof ProgressoCorpoRoute
  '/progresso/resumo': typeof ProgressoResumoRoute
  '/social/$userId': typeof SocialUserIdRoute
  '/social/seguidores': typeof SocialSeguidoresRoute
  '/wearables/callback': typeof WearablesCallbackRoute
  '/conteudo': typeof ConteudoIndexRoute
  '/governance': typeof GovernanceIndexRoute
  '/progresso': typeof ProgressoIndexRoute
  '/social': typeof SocialIndexRoute
  '/treino': typeof TreinoIndexRoute
  '/api/cron/daily-pushes': typeof ApiCronDailyPushesRoute
  '/api/shopify/webhook': typeof ApiShopifyWebhookRoute
  '/treino/exercicio/$id': typeof TreinoExercicioIdRoute
  '/treino/historico/$sessionId': typeof TreinoHistoricoSessionIdRoute
  '/treino/sessao/$id': typeof TreinoSessaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/clubes': typeof ClubesRoute
  '/coach': typeof CoachRoute
  '/desafios': typeof DesafiosRoute
  '/entrar': typeof EntrarRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/hubs': typeof HubsRouteWithChildren
  '/nutricao': typeof NutricaoRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRouteWithChildren
  '/social': typeof SocialRouteWithChildren
  '/suplementos': typeof SuplementosRoute
  '/termos': typeof TermosRoute
  '/welcome': typeof WelcomeRoute
  '/conteudo/$id': typeof ConteudoIdRoute
  '/governance/agents': typeof GovernanceAgentsRoute
  '/governance/cost': typeof GovernanceCostRoute
  '/governance/decisions': typeof GovernanceDecisionsRoute
  '/governance/evaluation': typeof GovernanceEvaluationRoute
  '/governance/overview': typeof GovernanceOverviewRoute
  '/governance/rag': typeof GovernanceRagRoute
  '/governance/runs': typeof GovernanceRunsRoute
  '/governance/safety': typeof GovernanceSafetyRoute
  '/hubs/$slug': typeof HubsSlugRoute
  '/progresso/corpo': typeof ProgressoCorpoRoute
  '/progresso/resumo': typeof ProgressoResumoRoute
  '/social/$userId': typeof SocialUserIdRoute
  '/social/seguidores': typeof SocialSeguidoresRoute
  '/wearables/callback': typeof WearablesCallbackRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/progresso/': typeof ProgressoIndexRoute
  '/social/': typeof SocialIndexRoute
  '/treino/': typeof TreinoIndexRoute
  '/api/cron/daily-pushes': typeof ApiCronDailyPushesRoute
  '/api/shopify/webhook': typeof ApiShopifyWebhookRoute
  '/treino/exercicio/$id': typeof TreinoExercicioIdRoute
  '/treino/historico/$sessionId': typeof TreinoHistoricoSessionIdRoute
  '/treino/sessao/$id': typeof TreinoSessaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/admin'
    | '/cadastro'
    | '/clubes'
    | '/coach'
    | '/desafios'
    | '/entrar'
    | '/governance'
    | '/hubs'
    | '/nutricao'
    | '/onboarding'
    | '/perfil'
    | '/privacidade'
    | '/progresso'
    | '/social'
    | '/suplementos'
    | '/termos'
    | '/welcome'
    | '/conteudo/$id'
    | '/governance/agents'
    | '/governance/cost'
    | '/governance/decisions'
    | '/governance/evaluation'
    | '/governance/overview'
    | '/governance/rag'
    | '/governance/runs'
    | '/governance/safety'
    | '/hubs/$slug'
    | '/progresso/corpo'
    | '/progresso/resumo'
    | '/social/$userId'
    | '/social/seguidores'
    | '/wearables/callback'
    | '/conteudo/'
    | '/governance/'
    | '/progresso/'
    | '/social/'
    | '/treino/'
    | '/api/cron/daily-pushes'
    | '/api/shopify/webhook'
    | '/treino/exercicio/$id'
    | '/treino/historico/$sessionId'
    | '/treino/sessao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/admin'
    | '/cadastro'
    | '/clubes'
    | '/coach'
    | '/desafios'
    | '/entrar'
    | '/hubs'
    | '/nutricao'
    | '/onboarding'
    | '/perfil'
    | '/privacidade'
    | '/suplementos'
    | '/termos'
    | '/welcome'
    | '/conteudo/$id'
    | '/governance/agents'
    | '/governance/cost'
    | '/governance/decisions'
    | '/governance/evaluation'
    | '/governance/overview'
    | '/governance/rag'
    | '/governance/runs'
    | '/governance/safety'
    | '/hubs/$slug'
    | '/progresso/corpo'
    | '/progresso/resumo'
    | '/social/$userId'
    | '/social/seguidores'
    | '/wearables/callback'
    | '/conteudo'
    | '/governance'
    | '/progresso'
    | '/social'
    | '/treino'
    | '/api/cron/daily-pushes'
    | '/api/shopify/webhook'
    | '/treino/exercicio/$id'
    | '/treino/historico/$sessionId'
    | '/treino/sessao/$id'
  id:
    | '__root__'
    | '/'
    | '/acesso'
    | '/admin'
    | '/cadastro'
    | '/clubes'
    | '/coach'
    | '/desafios'
    | '/entrar'
    | '/governance'
    | '/hubs'
    | '/nutricao'
    | '/onboarding'
    | '/perfil'
    | '/privacidade'
    | '/progresso'
    | '/social'
    | '/suplementos'
    | '/termos'
    | '/welcome'
    | '/conteudo/$id'
    | '/governance/agents'
    | '/governance/cost'
    | '/governance/decisions'
    | '/governance/evaluation'
    | '/governance/overview'
    | '/governance/rag'
    | '/governance/runs'
    | '/governance/safety'
    | '/hubs/$slug'
    | '/progresso/corpo'
    | '/progresso/resumo'
    | '/social/$userId'
    | '/social/seguidores'
    | '/wearables/callback'
    | '/conteudo/'
    | '/governance/'
    | '/progresso/'
    | '/social/'
    | '/treino/'
    | '/api/cron/daily-pushes'
    | '/api/shopify/webhook'
    | '/treino/exercicio/$id'
    | '/treino/historico/$sessionId'
    | '/treino/sessao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRoute: typeof AcessoRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  ClubesRoute: typeof ClubesRoute
  CoachRoute: typeof CoachRoute
  DesafiosRoute: typeof DesafiosRoute
  EntrarRoute: typeof EntrarRoute
  GovernanceRoute: typeof GovernanceRouteWithChildren
  HubsRoute: typeof HubsRouteWithChildren
  NutricaoRoute: typeof NutricaoRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProgressoRoute: typeof ProgressoRouteWithChildren
  SocialRoute: typeof SocialRouteWithChildren
  SuplementosRoute: typeof SuplementosRoute
  TermosRoute: typeof TermosRoute
  WelcomeRoute: typeof WelcomeRoute
  ConteudoIdRoute: typeof ConteudoIdRoute
  WearablesCallbackRoute: typeof WearablesCallbackRoute
  ConteudoIndexRoute: typeof ConteudoIndexRoute
  TreinoIndexRoute: typeof TreinoIndexRoute
  ApiCronDailyPushesRoute: typeof ApiCronDailyPushesRoute
  ApiShopifyWebhookRoute: typeof ApiShopifyWebhookRoute
  TreinoExercicioIdRoute: typeof TreinoExercicioIdRoute
  TreinoHistoricoSessionIdRoute: typeof TreinoHistoricoSessionIdRoute
  TreinoSessaoIdRoute: typeof TreinoSessaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs': {
      id: '/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof HubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao': {
      id: '/nutricao'
      path: '/nutricao'
      fullPath: '/nutricao'
      preLoaderRoute: typeof NutricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suplementos': {
      id: '/suplementos'
      path: '/suplementos'
      fullPath: '/suplementos'
      preLoaderRoute: typeof SuplementosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/': {
      id: '/conteudo/'
      path: '/conteudo'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof ConteudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/$id': {
      id: '/conteudo/$id'
      path: '/conteudo/$id'
      fullPath: '/conteudo/$id'
      preLoaderRoute: typeof ConteudoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/': {
      id: '/governance/'
      path: '/'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/agents': {
      id: '/governance/agents'
      path: '/agents'
      fullPath: '/governance/agents'
      preLoaderRoute: typeof GovernanceAgentsRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/cost': {
      id: '/governance/cost'
      path: '/cost'
      fullPath: '/governance/cost'
      preLoaderRoute: typeof GovernanceCostRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/decisions': {
      id: '/governance/decisions'
      path: '/decisions'
      fullPath: '/governance/decisions'
      preLoaderRoute: typeof GovernanceDecisionsRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/evaluation': {
      id: '/governance/evaluation'
      path: '/evaluation'
      fullPath: '/governance/evaluation'
      preLoaderRoute: typeof GovernanceEvaluationRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/overview': {
      id: '/governance/overview'
      path: '/overview'
      fullPath: '/governance/overview'
      preLoaderRoute: typeof GovernanceOverviewRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/rag': {
      id: '/governance/rag'
      path: '/rag'
      fullPath: '/governance/rag'
      preLoaderRoute: typeof GovernanceRagRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/runs': {
      id: '/governance/runs'
      path: '/runs'
      fullPath: '/governance/runs'
      preLoaderRoute: typeof GovernanceRunsRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/safety': {
      id: '/governance/safety'
      path: '/safety'
      fullPath: '/governance/safety'
      preLoaderRoute: typeof GovernanceSafetyRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/hubs/$slug': {
      id: '/hubs/$slug'
      path: '/$slug'
      fullPath: '/hubs/$slug'
      preLoaderRoute: typeof HubsSlugRouteImport
      parentRoute: typeof HubsRoute
    }
    '/progresso/': {
      id: '/progresso/'
      path: '/'
      fullPath: '/progresso/'
      preLoaderRoute: typeof ProgressoIndexRouteImport
      parentRoute: typeof ProgressoRoute
    }
    '/progresso/corpo': {
      id: '/progresso/corpo'
      path: '/corpo'
      fullPath: '/progresso/corpo'
      preLoaderRoute: typeof ProgressoCorpoRouteImport
      parentRoute: typeof ProgressoRoute
    }
    '/progresso/resumo': {
      id: '/progresso/resumo'
      path: '/resumo'
      fullPath: '/progresso/resumo'
      preLoaderRoute: typeof ProgressoResumoRouteImport
      parentRoute: typeof ProgressoRoute
    }
    '/social/': {
      id: '/social/'
      path: '/'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/$userId': {
      id: '/social/$userId'
      path: '/$userId'
      fullPath: '/social/$userId'
      preLoaderRoute: typeof SocialUserIdRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/seguidores': {
      id: '/social/seguidores'
      path: '/seguidores'
      fullPath: '/social/seguidores'
      preLoaderRoute: typeof SocialSeguidoresRouteImport
      parentRoute: typeof SocialRoute
    }
    '/treino/': {
      id: '/treino/'
      path: '/treino'
      fullPath: '/treino/'
      preLoaderRoute: typeof TreinoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wearables/callback': {
      id: '/wearables/callback'
      path: '/wearables/callback'
      fullPath: '/wearables/callback'
      preLoaderRoute: typeof WearablesCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-pushes': {
      id: '/api/cron/daily-pushes'
      path: '/api/cron/daily-pushes'
      fullPath: '/api/cron/daily-pushes'
      preLoaderRoute: typeof ApiCronDailyPushesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/webhook': {
      id: '/api/shopify/webhook'
      path: '/api/shopify/webhook'
      fullPath: '/api/shopify/webhook'
      preLoaderRoute: typeof ApiShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/exercicio/$id': {
      id: '/treino/exercicio/$id'
      path: '/treino/exercicio/$id'
      fullPath: '/treino/exercicio/$id'
      preLoaderRoute: typeof TreinoExercicioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/historico/$sessionId': {
      id: '/treino/historico/$sessionId'
      path: '/treino/historico/$sessionId'
      fullPath: '/treino/historico/$sessionId'
      preLoaderRoute: typeof TreinoHistoricoSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/sessao/$id': {
      id: '/treino/sessao/$id'
      path: '/treino/sessao/$id'
      fullPath: '/treino/sessao/$id'
      preLoaderRoute: typeof TreinoSessaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GovernanceRouteChildren {
  GovernanceAgentsRoute: typeof GovernanceAgentsRoute
  GovernanceCostRoute: typeof GovernanceCostRoute
  GovernanceDecisionsRoute: typeof GovernanceDecisionsRoute
  GovernanceEvaluationRoute: typeof GovernanceEvaluationRoute
  GovernanceOverviewRoute: typeof GovernanceOverviewRoute
  GovernanceRagRoute: typeof GovernanceRagRoute
  GovernanceRunsRoute: typeof GovernanceRunsRoute
  GovernanceSafetyRoute: typeof GovernanceSafetyRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
}

const GovernanceRouteChildren: GovernanceRouteChildren = {
  GovernanceAgentsRoute: GovernanceAgentsRoute,
  GovernanceCostRoute: GovernanceCostRoute,
  GovernanceDecisionsRoute: GovernanceDecisionsRoute,
  GovernanceEvaluationRoute: GovernanceEvaluationRoute,
  GovernanceOverviewRoute: GovernanceOverviewRoute,
  GovernanceRagRoute: GovernanceRagRoute,
  GovernanceRunsRoute: GovernanceRunsRoute,
  GovernanceSafetyRoute: GovernanceSafetyRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
}

const GovernanceRouteWithChildren = GovernanceRoute._addFileChildren(
  GovernanceRouteChildren,
)

interface HubsRouteChildren {
  HubsSlugRoute: typeof HubsSlugRoute
}

const HubsRouteChildren: HubsRouteChildren = {
  HubsSlugRoute: HubsSlugRoute,
}

const HubsRouteWithChildren = HubsRoute._addFileChildren(HubsRouteChildren)

interface ProgressoRouteChildren {
  ProgressoCorpoRoute: typeof ProgressoCorpoRoute
  ProgressoResumoRoute: typeof ProgressoResumoRoute
  ProgressoIndexRoute: typeof ProgressoIndexRoute
}

const ProgressoRouteChildren: ProgressoRouteChildren = {
  ProgressoCorpoRoute: ProgressoCorpoRoute,
  ProgressoResumoRoute: ProgressoResumoRoute,
  ProgressoIndexRoute: ProgressoIndexRoute,
}

const ProgressoRouteWithChildren = ProgressoRoute._addFileChildren(
  ProgressoRouteChildren,
)

interface SocialRouteChildren {
  SocialUserIdRoute: typeof SocialUserIdRoute
  SocialSeguidoresRoute: typeof SocialSeguidoresRoute
  SocialIndexRoute: typeof SocialIndexRoute
}

const SocialRouteChildren: SocialRouteChildren = {
  SocialUserIdRoute: SocialUserIdRoute,
  SocialSeguidoresRoute: SocialSeguidoresRoute,
  SocialIndexRoute: SocialIndexRoute,
}

const SocialRouteWithChildren =
  SocialRoute._addFileChildren(SocialRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRoute: AcessoRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  ClubesRoute: ClubesRoute,
  CoachRoute: CoachRoute,
  DesafiosRoute: DesafiosRoute,
  EntrarRoute: EntrarRoute,
  GovernanceRoute: GovernanceRouteWithChildren,
  HubsRoute: HubsRouteWithChildren,
  NutricaoRoute: NutricaoRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProgressoRoute: ProgressoRouteWithChildren,
  SocialRoute: SocialRouteWithChildren,
  SuplementosRoute: SuplementosRoute,
  TermosRoute: TermosRoute,
  WelcomeRoute: WelcomeRoute,
  ConteudoIdRoute: ConteudoIdRoute,
  WearablesCallbackRoute: WearablesCallbackRoute,
  ConteudoIndexRoute: ConteudoIndexRoute,
  TreinoIndexRoute: TreinoIndexRoute,
  ApiCronDailyPushesRoute: ApiCronDailyPushesRoute,
  ApiShopifyWebhookRoute: ApiShopifyWebhookRoute,
  TreinoExercicioIdRoute: TreinoExercicioIdRoute,
  TreinoHistoricoSessionIdRoute: TreinoHistoricoSessionIdRoute,
  TreinoSessaoIdRoute: TreinoSessaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
