-- Fase 3 — Unified Exercise Catalog
-- Overlay columns + Soldiers lote 1 seed. ON CONFLICT DO NOTHING preserves existing CMS rows.
-- Do not import third-party catalogs.

ALTER TABLE public.catalog_exercises
  ADD COLUMN IF NOT EXISTS canonical_name text,
  ADD COLUMN IF NOT EXISTS display_name_en text,
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS aliases text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS search_terms text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS equipment_inventory text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS exercise_family text,
  ADD COLUMN IF NOT EXISTS movement_family text,
  ADD COLUMN IF NOT EXISTS progression_family text,
  ADD COLUMN IF NOT EXISTS regression_family text,
  ADD COLUMN IF NOT EXISTS contraindication_tags text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS media_id text,
  ADD COLUMN IF NOT EXISTS media_status text,
  ADD COLUMN IF NOT EXISTS animation_spec jsonb;

UPDATE public.catalog_exercises
SET canonical_name = id
WHERE canonical_name IS NULL OR btrim(canonical_name) = '';

UPDATE public.catalog_exercises
SET media_id = id
WHERE media_id IS NULL OR btrim(media_id) = '';

UPDATE public.catalog_exercises
SET media_status = 'missing'
WHERE media_status IS NULL OR btrim(media_status) = '';

CREATE INDEX IF NOT EXISTS catalog_exercises_aliases_gin
  ON public.catalog_exercises USING gin (aliases);

CREATE INDEX IF NOT EXISTS catalog_exercises_search_terms_gin
  ON public.catalog_exercises USING gin (search_terms);

INSERT INTO public.catalog_exercises (
  id,
  name,
  muscle_group,
  equipment,
  swap_group,
  joints,
  unit,
  base_load,
  priority,
  primary_muscles,
  secondary_muscles,
  movement_pattern,
  difficulty,
  planner_eligible,
  active,
  instructions,
  alternative_ids,
  canonical_name,
  version,
  media_id,
  media_status
) VALUES
(
    'supino-reto',
    'Supino reto',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    50,
    1,
    ARRAY['peito']::text[],
    ARRAY['triceps', 'ombros']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Deite no banco com os pés no chão e as escápulas estáveis.', 'Segure a barra um pouco além da largura dos ombros.', 'Desça a barra de forma controlada até próximo do peito.', 'Empurre até a extensão dos braços sem perder o contato das costas no banco.']::text[],
    '{}'::text[],
    'supino-reto',
    1,
    'supino-reto',
    'missing'
  ),
(
    'supino-inclinado-halter',
    'Supino inclinado com halteres',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    20,
    2,
    ARRAY['peito']::text[],
    ARRAY['triceps', 'ombros']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Ajuste o banco entre 30 e 45 graus.', 'Halteres na linha do peito, palmas à frente.', 'Empurre para cima convergindo levemente no topo.', 'Desça até o peito alongar sem perder estabilidade do ombro.']::text[],
    '{}'::text[],
    'supino-inclinado-halter',
    1,
    'supino-inclinado-halter',
    'missing'
  ),
(
    'flexao',
    'Flexão de braço',
    'peito',
    'ambos',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps', 'core']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Mãos na largura dos ombros, corpo em linha reta.', 'Desça o peito em direção ao chão.', 'Empurre até os braços estenderem.', 'Mantenha o core firme o tempo todo.']::text[],
    '{}'::text[],
    'flexao',
    1,
    'flexao',
    'missing'
  ),
(
    'crucifixo',
    'Crucifixo',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    14,
    1,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Deite no banco com halteres acima do peito, cotovelos levemente flexionados.', 'Abra os braços em arco até sentir o peito alongar.', 'Feche o arco até os halteres se aproximarem no topo.', 'Não deixe os cotovelos travarem.']::text[],
    '{}'::text[],
    'crucifixo',
    1,
    'crucifixo',
    'missing'
  ),
(
    'supino-declinado',
    'Supino declinado',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    45,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Trave os pés no banco declinado.', 'Desça a barra à parte baixa do peito.', 'Empurre em linha controlada.', 'Não deixe os ombros subirem.']::text[],
    '{}'::text[],
    'supino-declinado',
    1,
    'supino-declinado',
    'missing'
  ),
(
    'flexao-diamante',
    'Flexão diamante',
    'peito',
    'casa',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'advanced',
    true,
    true,
    ARRAY['Junte os indicadores e polegares em losango sob o peito.', 'Desça com cotovelos junto ao tronco.', 'Empurre sem abrir o losango.', 'Mantenha o quadril alinhado.']::text[],
    '{}'::text[],
    'flexao-diamante',
    1,
    'flexao-diamante',
    'missing'
  ),
(
    'crossover-polia',
    'Crossover na polia',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    12,
    2,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Passo à frente, tronco estável.', 'Traga as polias em arco até a frente do peito.', 'Controle a volta.', 'Cotovelos levemente flexionados.']::text[],
    '{}'::text[],
    'crossover-polia',
    1,
    'crossover-polia',
    'missing'
  ),
(
    'peck-deck',
    'Peck deck',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    30,
    2,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Encoste as escápulas no encosto.', 'Feche os braços até as almofadas se tocarem.', 'Abra com controle.', 'Não encoste os cotovelos atrás da linha do tronco.']::text[],
    '{}'::text[],
    'peck-deck',
    1,
    'peck-deck',
    'missing'
  ),
(
    'supino-maquina',
    'Supino na máquina',
    'peito',
    'academia',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    40,
    2,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Ajuste o assento para as pegadas na linha do peito.', 'Empurre até a extensão controlada.', 'Volte sem perder o contato das costas.', 'Expire na subida.']::text[],
    '{}'::text[],
    'supino-maquina',
    1,
    'supino-maquina',
    'missing'
  ),
(
    'flexao-inclinada',
    'Flexão inclinada',
    'peito',
    'casa',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Mãos em um banco ou parede, corpo alinhado.', 'Desça o peito em direção ao apoio.', 'Empurre até estender.', 'Útil para quem está começando.']::text[],
    '{}'::text[],
    'flexao-inclinada',
    1,
    'flexao-inclinada',
    'missing'
  ),
(
    'crucifixo-inclinado',
    'Crucifixo inclinado',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    10,
    2,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Banco 30 graus, arco amplo com cotovelos moles.', 'Abra até o peito alongar.', 'Feche sem bater os halteres.', 'Evite hiperextensão do ombro.']::text[],
    '{}'::text[],
    'crucifixo-inclinado',
    1,
    'crucifixo-inclinado',
    'missing'
  ),
(
    'flexao-declinada',
    'Flexão declinada',
    'peito',
    'casa',
    'peito-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['peito']::text[],
    ARRAY['ombros', 'triceps']::text[],
    'press',
    'advanced',
    true,
    true,
    ARRAY['Pés elevados em um banco.', 'Desça o peito ao chão.', 'Empurre mantendo o core.', 'Não deixe o quadril cair.']::text[],
    '{}'::text[],
    'flexao-declinada',
    1,
    'flexao-declinada',
    'missing'
  ),
(
    'barra-fixa',
    'Barra fixa',
    'costas',
    'ambos',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'advanced',
    true,
    true,
    ARRAY['Pegada pronada um pouco além dos ombros.', 'Puxe o peito em direção à barra.', 'Desça até os braços quase estenderem.', 'Evite balanço excessivo.']::text[],
    '{}'::text[],
    'barra-fixa',
    1,
    'barra-fixa',
    'missing'
  ),
(
    'remada-curvada',
    'Remada curvada',
    'costas',
    'academia',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    40,
    1,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'intermediate',
    true,
    true,
    ARRAY['Incline o tronco com coluna neutra.', 'Puxe a barra em direção ao umbigo.', 'Aperte as escápulas no topo.', 'Desça com controle sem arredondar as costas.']::text[],
    '{}'::text[],
    'remada-curvada',
    1,
    'remada-curvada',
    'missing'
  ),
(
    'remada-unilateral',
    'Remada unilateral',
    'costas',
    'ambos',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    20,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Apoie um joelho e uma mão no banco.', 'Puxe o halter até o quadril.', 'Desça sem girar o tronco.', 'Troque o lado.']::text[],
    '{}'::text[],
    'remada-unilateral',
    1,
    'remada-unilateral',
    'missing'
  ),
(
    'pulldown',
    'Puxada alta',
    'costas',
    'academia',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    45,
    1,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Sente com o peito aberto e pegada pronada.', 'Puxe a barra até a clavícula.', 'Controle a subida.', 'Não incline demais o tronco para trás.']::text[],
    '{}'::text[],
    'pulldown',
    1,
    'pulldown',
    'missing'
  ),
(
    'remada-baixa',
    'Remada baixa',
    'costas',
    'academia',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    40,
    1,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Pés na plataforma, tronco estável.', 'Puxe o cabo ao umbigo.', 'Escápulas juntas no final.', 'Estenda os braços na volta.']::text[],
    '{}'::text[],
    'remada-baixa',
    1,
    'remada-baixa',
    'missing'
  ),
(
    'pullover',
    'Pullover',
    'costas',
    'academia',
    'costas-pull',
    ARRAY['ombro']::text[],
    'kg',
    16,
    3,
    ARRAY['costas']::text[],
    ARRAY['peito', 'core']::text[],
    'pull',
    'intermediate',
    true,
    true,
    ARRAY['Deite e leve o halter atrás da cabeça com cotovelos moles.', 'Puxe o halter de volta sobre o peito.', 'Sinta o alongamento da grande dorsal.', 'Não arqueie demais a lombar.']::text[],
    '{}'::text[],
    'pullover',
    1,
    'pullover',
    'missing'
  ),
(
    'barra-fixa-supinada',
    'Barra fixa supinada',
    'costas',
    'ambos',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'advanced',
    true,
    true,
    ARRAY['Pegada supinada na largura dos ombros.', 'Puxe o peito à barra.', 'Desça controlado.', 'Evite encolher os ombros.']::text[],
    '{}'::text[],
    'barra-fixa-supinada',
    1,
    'barra-fixa-supinada',
    'missing'
  ),
(
    'remada-cavalinho',
    'Remada cavalinho',
    'costas',
    'academia',
    'costas-row',
    ARRAY['lombar', 'punho']::text[],
    'kg',
    35,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'intermediate',
    true,
    true,
    ARRAY['Peito no apoio da máquina.', 'Puxe os cotovelos para trás.', 'Aperte as escápulas.', 'Não levante o tronco do apoio.']::text[],
    '{}'::text[],
    'remada-cavalinho',
    1,
    'remada-cavalinho',
    'missing'
  ),
(
    'face-pull',
    'Face pull',
    'costas',
    'academia',
    'costas-row',
    ARRAY['ombro']::text[],
    'kg',
    12,
    2,
    ARRAY['costas']::text[],
    ARRAY['ombros']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Polia alta com corda.', 'Puxe em direção ao rosto, cotovelos altos.', 'Gire os punhos para fora no final.', 'Controle a volta.']::text[],
    '{}'::text[],
    'face-pull',
    1,
    'face-pull',
    'missing'
  ),
(
    'remada-halter-peito',
    'Remada com peito apoiado',
    'costas',
    'academia',
    'costas-row',
    ARRAY['punho']::text[],
    'kg',
    16,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Deite de bruços no banco inclinado.', 'Reme os halteres até o banco.', 'Aperte as costas no topo.', 'Útil para isolar sem sobrecarregar a lombar.']::text[],
    '{}'::text[],
    'remada-halter-peito',
    1,
    'remada-halter-peito',
    'missing'
  ),
(
    'puxada-neutra',
    'Puxada pegada neutra',
    'costas',
    'academia',
    'costas-pull',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    40,
    2,
    ARRAY['costas']::text[],
    ARRAY['biceps']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Use o triangulo ou barra paralela.', 'Puxe até o peito alto.', 'Desça sem perder a postura.', 'Cotovelos próximos ao tronco.']::text[],
    '{}'::text[],
    'puxada-neutra',
    1,
    'puxada-neutra',
    'missing'
  ),
(
    'australian-row',
    'Remada australiana',
    'costas',
    'casa',
    'costas-row',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    3,
    ARRAY['costas']::text[],
    ARRAY['biceps', 'core']::text[],
    'pull',
    'beginner',
    true,
    true,
    ARRAY['Deite sob uma barra baixa, corpo rígido.', 'Puxe o peito até a barra.', 'Desça até os braços estenderem.', 'Quanto mais horizontal, mais difícil.']::text[],
    '{}'::text[],
    'australian-row',
    1,
    'australian-row',
    'missing'
  ),
(
    'encolhimento',
    'Encolhimento de ombros',
    'costas',
    'academia',
    'costas-row',
    '{}'::text[],
    'kg',
    40,
    3,
    ARRAY['costas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Barra ou halteres ao lado do corpo.', 'Eleve os ombros em direção às orelhas.', 'Desça com controle.', 'Não role os ombros para trás.']::text[],
    '{}'::text[],
    'encolhimento',
    1,
    'encolhimento',
    'missing'
  ),
(
    'agachamento',
    'Agachamento livre',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho', 'lombar']::text[],
    'kg',
    60,
    1,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'intermediate',
    true,
    true,
    ARRAY['Barra no trapézio, pés na largura dos ombros.', 'Desça com joelhos no rumo dos pés.', 'Suba empurrando o chão.', 'Mantenha o peito aberto.']::text[],
    '{}'::text[],
    'agachamento',
    1,
    'agachamento',
    'missing'
  ),
(
    'agachamento-corpo',
    'Agachamento com peso do corpo',
    'pernas',
    'ambos',
    'perna-squat',
    ARRAY['joelho']::text[],
    'corpo',
    0,
    3,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'beginner',
    true,
    true,
    ARRAY['Pés na largura do quadril.', 'Desça como se fosse sentar.', 'Suba sem jogar os joelhos para dentro.', 'Calcanhares no chão.']::text[],
    '{}'::text[],
    'agachamento-corpo',
    1,
    'agachamento-corpo',
    'missing'
  ),
(
    'leg-press',
    'Leg press',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    100,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'squat',
    'beginner',
    true,
    true,
    ARRAY['Pés na plataforma na largura do quadril.', 'Desça até cerca de 90 graus.', 'Empurre sem travar o joelho de forma brusca.', 'Lombar apoiada.']::text[],
    '{}'::text[],
    'leg-press',
    1,
    'leg-press',
    'missing'
  ),
(
    'afundo',
    'Afundo',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    12,
    1,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'intermediate',
    true,
    true,
    ARRAY['Dê um passo à frente.', 'Desça o joelho de trás em direção ao chão.', 'Suba sem perder o equilíbrio.', 'Tronco alto.']::text[],
    '{}'::text[],
    'afundo',
    1,
    'afundo',
    'missing'
  ),
(
    'terra-romeno',
    'Levantamento terra romeno',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    50,
    1,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'intermediate',
    true,
    true,
    ARRAY['Barra junto às coxas, joelhos moles.', 'Empurre o quadril para trás descendo a barra.', 'Sinta o posterior alongar.', 'Volte estendendo o quadril.']::text[],
    '{}'::text[],
    'terra-romeno',
    1,
    'terra-romeno',
    'missing'
  ),
(
    'panturrilha',
    'Panturrilha em pé',
    'pernas',
    'ambos',
    'perna-calf',
    '{}'::text[],
    'kg',
    20,
    1,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Antepé em um degrau, calcanhar livre.', 'Suba na ponta dos pés.', 'Desça alongando a panturrilha.', 'Movimento completo, sem bounce.']::text[],
    '{}'::text[],
    'panturrilha',
    1,
    'panturrilha',
    'missing'
  ),
(
    'agachamento-goblet',
    'Agachamento goblet',
    'pernas',
    'ambos',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    16,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'beginner',
    true,
    true,
    ARRAY['Segure um halter junto ao peito.', 'Desça entre os joelhos.', 'Suba empurrando o chão.', 'Cotovelos por dentro das coxas.']::text[],
    '{}'::text[],
    'agachamento-goblet',
    1,
    'agachamento-goblet',
    'missing'
  ),
(
    'agachamento-bulgaro',
    'Agachamento búlgaro',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    12,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'advanced',
    true,
    true,
    ARRAY['Pé de trás no banco.', 'Desça o joelho da frente até 90 graus.', 'Suba sem jogar o tronco à frente demais.', 'Troque o lado.']::text[],
    '{}'::text[],
    'agachamento-bulgaro',
    1,
    'agachamento-bulgaro',
    'missing'
  ),
(
    'stiff',
    'Stiff',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    40,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'intermediate',
    true,
    true,
    ARRAY['Joelhos quase estendidos.', 'Desça a barra próxima às pernas.', 'Suba contraindo o glúteo.', 'Coluna neutra.']::text[],
    '{}'::text[],
    'stiff',
    1,
    'stiff',
    'missing'
  ),
(
    'cadeira-extensora',
    'Cadeira extensora',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    30,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Ajuste o rolo acima do tornozelo.', 'Estenda os joelhos.', 'Desça controlado.', 'Evite estalo no travamento.']::text[],
    '{}'::text[],
    'cadeira-extensora',
    1,
    'cadeira-extensora',
    'missing'
  ),
(
    'mesa-flexora',
    'Mesa flexora',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['joelho']::text[],
    'kg',
    25,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Deite de bruços, rolo na panturrilha.', 'Flexione os calcanhares em direção ao glúteo.', 'Desça sem bater o peso.', 'Quadril no banco.']::text[],
    '{}'::text[],
    'mesa-flexora',
    1,
    'mesa-flexora',
    'missing'
  ),
(
    'hack-squat',
    'Hack squat',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho']::text[],
    'kg',
    50,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'intermediate',
    true,
    true,
    ARRAY['Costas no encosto, pés médios na plataforma.', 'Desça até a profundidade confortável.', 'Empurre pelos calcanhares.', 'Joelhos alinhados.']::text[],
    '{}'::text[],
    'hack-squat',
    1,
    'hack-squat',
    'missing'
  ),
(
    'passo-lateral',
    'Afundo lateral',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    8,
    3,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'intermediate',
    true,
    true,
    ARRAY['Passo largo para o lado.', 'Desça o quadril sobre a perna da frente.', 'Volte ao centro.', 'Pé de apoio firme.']::text[],
    '{}'::text[],
    'passo-lateral',
    1,
    'passo-lateral',
    'missing'
  ),
(
    'elevacao-pelvica',
    'Elevação pélvica',
    'pernas',
    'ambos',
    'perna-hinge',
    '{}'::text[],
    'kg',
    20,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'beginner',
    true,
    true,
    ARRAY['Ombros no banco, barra sobre o quadril.', 'Empurre o quadril para cima.', 'Aperte o glúteo no topo.', 'Desça com controle.']::text[],
    '{}'::text[],
    'elevacao-pelvica',
    1,
    'elevacao-pelvica',
    'missing'
  ),
(
    'panturrilha-sentado',
    'Panturrilha sentado',
    'pernas',
    'academia',
    'perna-calf',
    '{}'::text[],
    'kg',
    25,
    2,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Rolo sobre os joelhos.', 'Suba na ponta dos pés.', 'Desça alongando.', 'Pausa curta no topo.']::text[],
    '{}'::text[],
    'panturrilha-sentado',
    1,
    'panturrilha-sentado',
    'missing'
  ),
(
    'agachamento-sumo',
    'Agachamento sumô',
    'pernas',
    'academia',
    'perna-squat',
    ARRAY['joelho', 'lombar']::text[],
    'kg',
    50,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'squat',
    'intermediate',
    true,
    true,
    ARRAY['Pés bem abertos, pontas para fora.', 'Desça o quadril entre os joelhos.', 'Suba contraindo adutores e glúteo.', 'Peito alto.']::text[],
    '{}'::text[],
    'agachamento-sumo',
    1,
    'agachamento-sumo',
    'missing'
  ),
(
    'passada-caminhada',
    'Passada caminhando',
    'pernas',
    'ambos',
    'perna-lunge',
    ARRAY['joelho']::text[],
    'kg',
    10,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'lunge',
    'intermediate',
    true,
    true,
    ARRAY['Afundo contínuo para frente.', 'Joelho de trás desce perto do chão.', 'Alterne as pernas.', 'Passos estáveis.']::text[],
    '{}'::text[],
    'passada-caminhada',
    1,
    'passada-caminhada',
    'missing'
  ),
(
    'terra-convencional',
    'Levantamento terra',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar', 'joelho']::text[],
    'kg',
    70,
    1,
    ARRAY['pernas']::text[],
    ARRAY['costas', 'core']::text[],
    'hinge',
    'advanced',
    true,
    true,
    ARRAY['Barra sobre o meio do pé, quadril atrás.', 'Puxe a barra raspando as pernas.', 'Trave o quadril no topo.', 'Desça com a mesma trajetória.']::text[],
    '{}'::text[],
    'terra-convencional',
    1,
    'terra-convencional',
    'missing'
  ),
(
    'desenvolvimento',
    'Desenvolvimento militar',
    'ombros',
    'academia',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    30,
    1,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Barra na clavícula, core firme.', 'Empurre acima da cabeça.', 'Desça controlado à clavícula.', 'Não jogue a lombar à frente.']::text[],
    '{}'::text[],
    'desenvolvimento',
    1,
    'desenvolvimento',
    'missing'
  ),
(
    'elevacao-lateral',
    'Elevação lateral',
    'ombros',
    'ambos',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    8,
    1,
    ARRAY['ombros']::text[],
    '{}'::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Braços levemente flexionados ao lado do corpo.', 'Eleve até a linha dos ombros.', 'Desça com controle.', 'Não encolha o trapézio.']::text[],
    '{}'::text[],
    'elevacao-lateral',
    1,
    'elevacao-lateral',
    'missing'
  ),
(
    'pike-push',
    'Flexão pike',
    'ombros',
    'casa',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Quadril alto, corpo em V invertido.', 'Desça a cabeça entre as mãos.', 'Empurre de volta.', 'Peso nos ombros, não no peito.']::text[],
    '{}'::text[],
    'pike-push',
    1,
    'pike-push',
    'missing'
  ),
(
    'desenvolvimento-halter',
    'Desenvolvimento com halteres',
    'ombros',
    'ambos',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    12,
    1,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Sentado ou em pé, halteres na linha das orelhas.', 'Empurre para cima.', 'Desça até os cotovelos a 90 graus.', 'Punhos firmes.']::text[],
    '{}'::text[],
    'desenvolvimento-halter',
    1,
    'desenvolvimento-halter',
    'missing'
  ),
(
    'elevacao-frontal',
    'Elevação frontal',
    'ombros',
    'ambos',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    8,
    2,
    ARRAY['ombros']::text[],
    '{}'::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Halteres à frente das coxas.', 'Eleve até a linha dos ombros.', 'Desça lento.', 'Não balançe o tronco.']::text[],
    '{}'::text[],
    'elevacao-frontal',
    1,
    'elevacao-frontal',
    'missing'
  ),
(
    'remada-alta',
    'Remada alta',
    'ombros',
    'academia',
    'ombro-raise',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    20,
    3,
    ARRAY['ombros']::text[],
    ARRAY['costas']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Barra na frente das coxas.', 'Puxe até a clavícula, cotovelos altos.', 'Desça controlado.', 'Evite se a articulação do ombro incomodar.']::text[],
    '{}'::text[],
    'remada-alta',
    1,
    'remada-alta',
    'missing'
  ),
(
    'arnold-press',
    'Arnold press',
    'ombros',
    'academia',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    10,
    2,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'intermediate',
    true,
    true,
    ARRAY['Comece com palmas à frente do peito.', 'Gire e empurre acima da cabeça.', 'Volte girando as palmas.', 'Movimento contínuo.']::text[],
    '{}'::text[],
    'arnold-press',
    1,
    'arnold-press',
    'missing'
  ),
(
    'crucifixo-inverso',
    'Crucifixo inverso',
    'ombros',
    'academia',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    8,
    2,
    ARRAY['ombros']::text[],
    ARRAY['costas']::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Incline o tronco, halteres pendurados.', 'Abra os braços até a linha dos ombros.', 'Aperte o deltoide posterior.', 'Pescoço neutro.']::text[],
    '{}'::text[],
    'crucifixo-inverso',
    1,
    'crucifixo-inverso',
    'missing'
  ),
(
    'desenvolvimento-maquina',
    'Desenvolvimento na máquina',
    'ombros',
    'academia',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'kg',
    25,
    2,
    ARRAY['ombros']::text[],
    ARRAY['triceps']::text[],
    'press',
    'beginner',
    true,
    true,
    ARRAY['Ajuste o assento para as pegadas na linha dos ombros.', 'Empurre para cima.', 'Desça até 90 graus.', 'Costas no encosto.']::text[],
    '{}'::text[],
    'desenvolvimento-maquina',
    1,
    'desenvolvimento-maquina',
    'missing'
  ),
(
    'elevacao-lateral-polia',
    'Elevação lateral na polia',
    'ombros',
    'academia',
    'ombro-raise',
    ARRAY['ombro']::text[],
    'kg',
    6,
    2,
    ARRAY['ombros']::text[],
    '{}'::text[],
    'raise',
    'beginner',
    true,
    true,
    ARRAY['Polia baixa cruzada atrás do corpo.', 'Eleve o braço até a linha do ombro.', 'Desça sem perder a tensão.', 'Tronco estável.']::text[],
    '{}'::text[],
    'elevacao-lateral-polia',
    1,
    'elevacao-lateral-polia',
    'missing'
  ),
(
    'handstand-hold',
    'Parada de mãos na parede',
    'ombros',
    'casa',
    'ombro-press',
    ARRAY['ombro', 'punho']::text[],
    'min',
    0,
    3,
    ARRAY['ombros']::text[],
    ARRAY['core', 'triceps']::text[],
    'isometric',
    'advanced',
    true,
    true,
    ARRAY['Encontre a parede com os pés.', 'Trave ombros e core.', 'Respire sem desabar os ombros.', 'Desça com controle.']::text[],
    '{}'::text[],
    'handstand-hold',
    1,
    'handstand-hold',
    'missing'
  ),
(
    'rosca-direta',
    'Rosca direta',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    20,
    1,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Barra na largura dos ombros, cotovelos junto ao tronco.', 'Flexione até a barra chegar perto dos ombros.', 'Desça até quase estender.', 'Não jogue o tronco para trás.']::text[],
    '{}'::text[],
    'rosca-direta',
    1,
    'rosca-direta',
    'missing'
  ),
(
    'rosca-martelo',
    'Rosca martelo',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    12,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Halteres em pegada neutra.', 'Flexione até a altura do ombro.', 'Desça controlado.', 'Cotovelos parados.']::text[],
    '{}'::text[],
    'rosca-martelo',
    1,
    'rosca-martelo',
    'missing'
  ),
(
    'rosca-inclinada',
    'Rosca inclinada',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    10,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['Banco 45–60 graus, braços pendurados.', 'Flexione até o pico do bíceps.', 'Desça alongando.', 'Não encolha os ombros.']::text[],
    '{}'::text[],
    'rosca-inclinada',
    1,
    'rosca-inclinada',
    'missing'
  ),
(
    'rosca-scott',
    'Rosca scott',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    16,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['Braços apoiados no banco scott.', 'Flexione até o pico.', 'Desça sem estender por completo se o cotovelo incomodar.', 'Tronco colado no apoio.']::text[],
    '{}'::text[],
    'rosca-scott',
    1,
    'rosca-scott',
    'missing'
  ),
(
    'rosca-concentrada',
    'Rosca concentrada',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    10,
    3,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Cotovelo apoiado na coxa interna.', 'Flexione o halter até o ombro.', 'Desça lento.', 'Sem balanço.']::text[],
    '{}'::text[],
    'rosca-concentrada',
    1,
    'rosca-concentrada',
    'missing'
  ),
(
    'rosca-polia',
    'Rosca na polia',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    18,
    2,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'beginner',
    true,
    true,
    ARRAY['Polia baixa, barra reta ou W.', 'Flexione mantendo cotovelos fixos.', 'Tensão constante na volta.', 'Postura alta.']::text[],
    '{}'::text[],
    'rosca-polia',
    1,
    'rosca-polia',
    'missing'
  ),
(
    'rosca-banco',
    'Rosca no banco 21',
    'biceps',
    'ambos',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    12,
    3,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['7 reps da metade inferior, 7 da superior, 7 completas.', 'Cotovelos colados.', 'Carga moderada.', 'Respire a cada bloco.']::text[],
    '{}'::text[],
    'rosca-banco',
    1,
    'rosca-banco',
    'missing'
  ),
(
    'chin-hold',
    'Isometria na barra supinada',
    'biceps',
    'casa',
    'biceps-curl',
    ARRAY['ombro', 'punho']::text[],
    'min',
    0,
    3,
    ARRAY['biceps']::text[],
    ARRAY['costas']::text[],
    'isometric',
    'advanced',
    true,
    true,
    ARRAY['Puxe até o queixo ficar acima da barra.', 'Segure a posição.', 'Desça controlado ao final.', 'Ombros longe das orelhas.']::text[],
    '{}'::text[],
    'chin-hold',
    1,
    'chin-hold',
    'missing'
  ),
(
    'triceps-corda',
    'Tríceps na corda',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    20,
    1,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Cotovelos colados ao tronco.', 'Estenda a corda para baixo abrindo no final.', 'Volte até 90 graus.', 'Não abra os cotovelos para o lado.']::text[],
    '{}'::text[],
    'triceps-corda',
    1,
    'triceps-corda',
    'missing'
  ),
(
    'triceps-banco',
    'Tríceps no banco',
    'triceps',
    'ambos',
    'triceps-ext',
    ARRAY['punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['triceps']::text[],
    ARRAY['ombros']::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Mãos no banco atrás do corpo, pés à frente.', 'Desça flexionando os cotovelos.', 'Empurre até estender.', 'Ombros estáveis.']::text[],
    '{}'::text[],
    'triceps-banco',
    1,
    'triceps-banco',
    'missing'
  ),
(
    'triceps-testa',
    'Tríceps testa',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    16,
    1,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'intermediate',
    true,
    true,
    ARRAY['Deite, barra acima da testa.', 'Flexione só os cotovelos descendo a barra.', 'Estenda de volta.', 'Cotovelos apontando para cima.']::text[],
    '{}'::text[],
    'triceps-testa',
    1,
    'triceps-testa',
    'missing'
  ),
(
    'triceps-frances',
    'Tríceps francês',
    'triceps',
    'ambos',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    12,
    2,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'intermediate',
    true,
    true,
    ARRAY['Halter atrás da cabeça, cotovelos altos.', 'Estenda acima da cabeça.', 'Desça alongando o tríceps.', 'Não abra os cotovelos.']::text[],
    '{}'::text[],
    'triceps-frances',
    1,
    'triceps-frances',
    'missing'
  ),
(
    'mergulho-paralelas',
    'Mergulho nas paralelas',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['ombro', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['triceps']::text[],
    ARRAY['peito', 'ombros']::text[],
    'press',
    'advanced',
    true,
    true,
    ARRAY['Tronco mais vertical para ênfase no tríceps.', 'Desça até os ombros confortáveis.', 'Empurre até estender.', 'Não encolha o pescoço.']::text[],
    '{}'::text[],
    'mergulho-paralelas',
    1,
    'mergulho-paralelas',
    'missing'
  ),
(
    'triceps-coice',
    'Tríceps coice',
    'triceps',
    'ambos',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    8,
    3,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Tronco inclinado, cotovelo colado.', 'Estenda o halter para trás.', 'Volte até 90 graus.', 'Sem balanço.']::text[],
    '{}'::text[],
    'triceps-coice',
    1,
    'triceps-coice',
    'missing'
  ),
(
    'triceps-polia-barra',
    'Tríceps na polia com barra',
    'triceps',
    'academia',
    'triceps-ext',
    ARRAY['punho']::text[],
    'kg',
    22,
    2,
    ARRAY['triceps']::text[],
    '{}'::text[],
    'extension',
    'beginner',
    true,
    true,
    ARRAY['Barra reta na polia alta.', 'Estenda até os cotovelos travarem com controle.', 'Volte até o antebraço ficar paralelo.', 'Peito aberto.']::text[],
    '{}'::text[],
    'triceps-polia-barra',
    1,
    'triceps-polia-barra',
    'missing'
  ),
(
    'diamond-hold',
    'Isometria flexão diamante',
    'triceps',
    'casa',
    'triceps-ext',
    ARRAY['ombro', 'punho']::text[],
    'min',
    0,
    3,
    ARRAY['triceps']::text[],
    ARRAY['peito']::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['Desça até o meio da flexão diamante.', 'Segure a posição.', 'Core firme.', 'Suba ao final.']::text[],
    '{}'::text[],
    'diamond-hold',
    1,
    'diamond-hold',
    'missing'
  ),
(
    'prancha',
    'Prancha',
    'core',
    'ambos',
    'core-iso',
    '{}'::text[],
    'min',
    0,
    1,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'beginner',
    true,
    true,
    ARRAY['Antebraços e pontas dos pés no chão.', 'Corpo em linha reta.', 'Não deixe o quadril cair nem subir demais.', 'Respire sem perder a tensão.']::text[],
    '{}'::text[],
    'prancha',
    1,
    'prancha',
    'missing'
  ),
(
    'abdominal-remador',
    'Abdominal remador',
    'core',
    'ambos',
    'core-dyn',
    '{}'::text[],
    'corpo',
    0,
    1,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Deite, joelhos e tronco sobem juntos.', 'Estenda na volta sem bater no chão.', 'Movimento controlado.', 'Pescoço relaxado.']::text[],
    '{}'::text[],
    'abdominal-remador',
    1,
    'abdominal-remador',
    'missing'
  ),
(
    'hollow',
    'Hollow hold',
    'core',
    'ambos',
    'core-iso',
    ARRAY['lombar']::text[],
    'min',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['Lombar colada no chão.', 'Braços e pernas levemente elevados.', 'Mantenha a posição.', 'Se a lombar sair, encurte a alavanca.']::text[],
    '{}'::text[],
    'hollow',
    1,
    'hollow',
    'missing'
  ),
(
    'abdominal-infra',
    'Elevação de pernas',
    'core',
    'ambos',
    'core-dyn',
    ARRAY['lombar']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'intermediate',
    true,
    true,
    ARRAY['Deite ou pendure, pernas juntas.', 'Eleve até 90 graus.', 'Desça sem arquear a lombar.', 'Movimento lento.']::text[],
    '{}'::text[],
    'abdominal-infra',
    1,
    'abdominal-infra',
    'missing'
  ),
(
    'prancha-lateral',
    'Prancha lateral',
    'core',
    'ambos',
    'core-iso',
    '{}'::text[],
    'min',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['Apoio no antebraço, corpo de lado.', 'Quadril elevado.', 'Troque o lado.', 'Ombro empilhado sobre o cotovelo.']::text[],
    '{}'::text[],
    'prancha-lateral',
    1,
    'prancha-lateral',
    'missing'
  ),
(
    'ab-wheel',
    'Roda abdominal',
    'core',
    'ambos',
    'core-dyn',
    ARRAY['lombar', 'ombro']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    ARRAY['ombros']::text[],
    'mobility',
    'advanced',
    true,
    true,
    ARRAY['Joelhos no chão, roda à frente.', 'Role para frente sem deixar a lombar cair.', 'Volte contraindo o abdômen.', 'Amplitude que você controla.']::text[],
    '{}'::text[],
    'ab-wheel',
    1,
    'ab-wheel',
    'missing'
  ),
(
    'dead-bug',
    'Dead bug',
    'core',
    'casa',
    'core-dyn',
    ARRAY['lombar']::text[],
    'corpo',
    0,
    3,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Deite, braços e joelhos a 90 graus.', 'Estenda braço e perna opostos.', 'Volte e alterne.', 'Lombar colada.']::text[],
    '{}'::text[],
    'dead-bug',
    1,
    'dead-bug',
    'missing'
  ),
(
    'mountain-climber',
    'Mountain climber',
    'core',
    'casa',
    'core-dyn',
    ARRAY['joelho', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    ARRAY['cardio']::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Prancha alta.', 'Alterne os joelhos em direção ao peito.', 'Quadril estável.', 'Ritmo constante.']::text[],
    '{}'::text[],
    'mountain-climber',
    1,
    'mountain-climber',
    'missing'
  ),
(
    'pallof',
    'Pallof press',
    'core',
    'academia',
    'core-iso',
    '{}'::text[],
    'kg',
    10,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['De lado para a polia, cabo no peito.', 'Empurre os braços à frente resistindo à rotação.', 'Volte ao peito.', 'Quadril travado.']::text[],
    '{}'::text[],
    'pallof',
    1,
    'pallof',
    'missing'
  ),
(
    'crunch',
    'Abdominal crunch',
    'core',
    'casa',
    'core-dyn',
    '{}'::text[],
    'corpo',
    0,
    3,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Deite, joelhos dobrados.', 'Eleve as escápulas do chão.', 'Desça sem relaxar por completo.', 'Não puxe o pescoço.']::text[],
    '{}'::text[],
    'crunch',
    1,
    'crunch',
    'missing'
  ),
(
    'farmers-carry',
    'Farmer walk',
    'core',
    'academia',
    'core-iso',
    ARRAY['punho']::text[],
    'kg',
    24,
    2,
    ARRAY['core']::text[],
    ARRAY['ombros']::text[],
    'isometric',
    'intermediate',
    true,
    true,
    ARRAY['Halteres pesados ao lado do corpo.', 'Caminhe com tronco alto.', 'Passos curtos e estáveis.', 'Ombros longe das orelhas.']::text[],
    '{}'::text[],
    'farmers-carry',
    1,
    'farmers-carry',
    'missing'
  ),
(
    'russian-twist',
    'Russian twist',
    'core',
    'ambos',
    'core-dyn',
    '{}'::text[],
    'kg',
    6,
    3,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'intermediate',
    true,
    true,
    ARRAY['Sentado, tronco recuado, pés elevados se possível.', 'Gire o implemento de um lado ao outro.', 'Respire a cada giro.', 'Não arredonde demais a lombar.']::text[],
    '{}'::text[],
    'russian-twist',
    1,
    'russian-twist',
    'missing'
  ),
(
    'corrida',
    'Corrida contínua',
    'cardio',
    'ambos',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'min',
    0,
    1,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Ritmo conversável.', 'Passada leve, tronco alto.', 'Respire pelo nariz e boca conforme precisar.', 'Termine com desaquecimento.']::text[],
    '{}'::text[],
    'corrida',
    1,
    'corrida',
    'missing'
  ),
(
    'hiit-bike',
    'HIIT na bike',
    'cardio',
    'academia',
    'cardio-hiit',
    '{}'::text[],
    'min',
    0,
    1,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Alterne sprints curtos e recuperação.', 'Postura firme no selim.', 'Não prenda a respiração.', 'Ajuste a carga para completar os intervalos.']::text[],
    '{}'::text[],
    'hiit-bike',
    1,
    'hiit-bike',
    'missing'
  ),
(
    'burpee',
    'Burpee',
    'cardio',
    'ambos',
    'cardio-hiit',
    ARRAY['joelho', 'punho']::text[],
    'corpo',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['peito', 'core']::text[],
    'cardio',
    'advanced',
    true,
    true,
    ARRAY['Agache, mãos no chão, jogue os pés para trás.', 'Flexão opcional, volte os pés e salte.', 'Ritmo sustentável.', 'Aterrisse macio.']::text[],
    '{}'::text[],
    'burpee',
    1,
    'burpee',
    'missing'
  ),
(
    'pular-corda',
    'Pular corda',
    'cardio',
    'ambos',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Saltos baixos na ponta dos pés.', 'Punhos giram a corda, não os braços inteiros.', 'Ritmo constante.', 'Joelhos moles.']::text[],
    '{}'::text[],
    'pular-corda',
    1,
    'pular-corda',
    'missing'
  ),
(
    'remo-ergometro',
    'Remo ergômetro',
    'cardio',
    'academia',
    'cardio-steady',
    ARRAY['joelho', 'lombar']::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['costas']::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Pernas, quadril e braços nessa ordem.', 'Volta reversa: braços, quadril, pernas.', 'Cadência estável.', 'Não arredonde as costas.']::text[],
    '{}'::text[],
    'remo-ergometro',
    1,
    'remo-ergometro',
    'missing'
  ),
(
    'eliptico',
    'Elíptico',
    'cardio',
    'academia',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'min',
    0,
    3,
    ARRAY['cardio']::text[],
    '{}'::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Postura alta, impulso nos pés e braços.', 'Cadência constante.', 'Não trave os joelhos.', 'Use para baixo impacto.']::text[],
    '{}'::text[],
    'eliptico',
    1,
    'eliptico',
    'missing'
  ),
(
    'jumping-jack',
    'Polichinelo',
    'cardio',
    'casa',
    'cardio-hiit',
    ARRAY['joelho']::text[],
    'corpo',
    0,
    3,
    ARRAY['cardio']::text[],
    ARRAY['ombros']::text[],
    'cardio',
    'beginner',
    true,
    true,
    ARRAY['Salte abrindo pés e braços.', 'Volte ao centro.', 'Ritmo constante.', 'Aterrisse macio.']::text[],
    '{}'::text[],
    'jumping-jack',
    1,
    'jumping-jack',
    'missing'
  ),
(
    'battle-rope',
    'Corda naval',
    'cardio',
    'academia',
    'cardio-hiit',
    ARRAY['ombro']::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['core']::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Joelhos moles, tronco estável.', 'Ondas alternadas com as cordas.', 'Intervalos curtos.', 'Não encolha os ombros.']::text[],
    '{}'::text[],
    'battle-rope',
    1,
    'battle-rope',
    'missing'
  ),
(
    'subida-caixa',
    'Subida na caixa',
    'cardio',
    'ambos',
    'cardio-steady',
    ARRAY['joelho']::text[],
    'corpo',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['pernas']::text[],
    'lunge',
    'beginner',
    true,
    true,
    ARRAY['Pise com o pé inteiro na caixa.', 'Suba estendendo o quadril.', 'Desça com controle.', 'Alterne as pernas.']::text[],
    '{}'::text[],
    'subida-caixa',
    1,
    'subida-caixa',
    'missing'
  ),
(
    'assalto-bike',
    'Assault bike',
    'cardio',
    'academia',
    'cardio-hiit',
    '{}'::text[],
    'min',
    0,
    2,
    ARRAY['cardio']::text[],
    ARRAY['ombros']::text[],
    'cardio',
    'advanced',
    true,
    true,
    ARRAY['Empurre e puxe os braços junto com as pernas.', 'Sprints curtos.', 'Recupere sem parar de pedalar.', 'Tronco estável.']::text[],
    '{}'::text[],
    'assalto-bike',
    1,
    'assalto-bike',
    'missing'
  ),
(
    'crucifixo-polia-baixa',
    'Crucifixo na polia baixa',
    'peito',
    'academia',
    'peito-fly',
    ARRAY['ombro']::text[],
    'kg',
    10,
    3,
    ARRAY['peito']::text[],
    ARRAY['ombros']::text[],
    'raise',
    'intermediate',
    true,
    true,
    ARRAY['Polias baixas, passo à frente.', 'Suba os cabos em arco até a frente do peito.', 'Desça alongando.', 'Cotovelos moles.']::text[],
    '{}'::text[],
    'crucifixo-polia-baixa',
    1,
    'crucifixo-polia-baixa',
    'missing'
  ),
(
    'good-morning',
    'Good morning',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    30,
    3,
    ARRAY['pernas']::text[],
    ARRAY['core']::text[],
    'hinge',
    'advanced',
    true,
    true,
    ARRAY['Barra no trapézio, joelhos moles.', 'Incline o tronco empurrando o quadril para trás.', 'Volte estendendo o quadril.', 'Carga conservadora.']::text[],
    '{}'::text[],
    'good-morning',
    1,
    'good-morning',
    'missing'
  ),
(
    'adutora',
    'Cadeira adutora',
    'pernas',
    'academia',
    'perna-squat',
    '{}'::text[],
    'kg',
    30,
    3,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Joelhos nas almofadas da máquina.', 'Feche as pernas contra a resistência.', 'Abra com controle.', 'Tronco apoiado.']::text[],
    '{}'::text[],
    'adutora',
    1,
    'adutora',
    'missing'
  ),
(
    'abdutora',
    'Cadeira abdutora',
    'pernas',
    'academia',
    'perna-squat',
    '{}'::text[],
    'kg',
    30,
    3,
    ARRAY['pernas']::text[],
    '{}'::text[],
    'mobility',
    'beginner',
    true,
    true,
    ARRAY['Joelhos nas almofadas.', 'Abra as pernas contra a resistência.', 'Feche controlado.', 'Não arqueie a lombar.']::text[],
    '{}'::text[],
    'abdutora',
    1,
    'abdutora',
    'missing'
  ),
(
    'rosca-inversa',
    'Rosca inversa',
    'biceps',
    'academia',
    'biceps-curl',
    ARRAY['punho']::text[],
    'kg',
    12,
    3,
    ARRAY['biceps']::text[],
    '{}'::text[],
    'curl',
    'intermediate',
    true,
    true,
    ARRAY['Pegada pronada na barra.', 'Flexione até a barra chegar perto dos ombros.', 'Desça lento.', 'Punhos firmes.']::text[],
    '{}'::text[],
    'rosca-inversa',
    1,
    'rosca-inversa',
    'missing'
  ),
(
    'hanging-knee-raise',
    'Elevação de joelhos na barra',
    'core',
    'ambos',
    'core-dyn',
    ARRAY['ombro']::text[],
    'corpo',
    0,
    2,
    ARRAY['core']::text[],
    '{}'::text[],
    'mobility',
    'intermediate',
    true,
    true,
    ARRAY['Pendure na barra, ombros ativos.', 'Eleve os joelhos ao peito.', 'Desça sem balanço excessivo.', 'Não encolha o pescoço.']::text[],
    '{}'::text[],
    'hanging-knee-raise',
    1,
    'hanging-knee-raise',
    'missing'
  ),
(
    'kettlebell-swing',
    'Swing com kettlebell',
    'pernas',
    'academia',
    'perna-hinge',
    ARRAY['lombar']::text[],
    'kg',
    16,
    2,
    ARRAY['pernas']::text[],
    ARRAY['core', 'ombros']::text[],
    'hinge',
    'intermediate',
    true,
    true,
    ARRAY['Hinge, kettlebell entre as pernas.', 'Estenda o quadril projetando o peso à frente.', 'Deixe o peso flutuar até a linha dos ombros.', 'Não levante com os braços.']::text[],
    '{}'::text[],
    'kettlebell-swing',
    1,
    'kettlebell-swing',
    'missing'
  ),
(
    'ski-erg',
    'SkiErg',
    'cardio',
    'academia',
    'cardio-hiit',
    ARRAY['ombro']::text[],
    'min',
    0,
    3,
    ARRAY['cardio']::text[],
    ARRAY['core']::text[],
    'cardio',
    'intermediate',
    true,
    true,
    ARRAY['Puxe as alças de cima para baixo com o quadril.', 'Estenda o quadril no final da puxada.', 'Recupere os braços alto.', 'Cadência rítmica.']::text[],
    '{}'::text[],
    'ski-erg',
    1,
    'ski-erg',
    'missing'
  )
ON CONFLICT (id) DO NOTHING;
